import { StyleSheet } from 'react-native';
import { lightTheme, radii, spacing, typography } from '../../../theme/tokens';

export const chatStyles = StyleSheet.create({
  container: { flex: 1 },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingBottom: spacing.md,
    paddingTop: spacing.sm,
    borderBottomWidth: 1,
    gap: spacing.sm,
  },
  backBtn: { marginBottom: 0 },
  headerAvatar: { width: 44, height: 44, borderRadius: 22 },
  headerInfo: { flex: 1, gap: 2 },
  quickActionTrigger: { width: 38, height: 38, borderRadius: 19, alignItems: 'center', justifyContent: 'center' },
  headerEyebrow: { fontSize: 10, fontWeight: '800', letterSpacing: 1.6 },
  headerName: { fontSize: typography.h3, fontWeight: '800', letterSpacing: -0.3 },
  headerTag: {
    alignSelf: 'flex-start',
    borderRadius: radii.pill,
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
    marginTop: spacing.xs,
  },
  headerTagText: { fontSize: 10, fontWeight: '700' },
  listContent: { paddingHorizontal: spacing.lg, paddingVertical: spacing.lg },
  bubble: {
    paddingHorizontal: spacing.md,
    paddingVertical: spacing.sm + 2,
    borderRadius: radii.lg,
    marginBottom: spacing.sm,
    maxWidth: '82%',
  },
  bubbleMe: { alignSelf: 'flex-end', borderBottomRightRadius: 4 },
  bubbleThem: { alignSelf: 'flex-start', borderBottomLeftRadius: 4 },
  bubbleText: { fontSize: typography.body, lineHeight: 22 },
  statusNote: { textAlign: 'center', fontSize: typography.caption, paddingVertical: spacing.xs },
  errorNote: {
    textAlign: 'center',
    fontSize: typography.caption,
    paddingVertical: spacing.xs,
    fontWeight: '600',
  },
  inputBar: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.sm,
    borderTopWidth: 1,
    gap: spacing.sm,
    paddingBottom: spacing.md,
  },
  input: {
    flex: 1,
    borderRadius: 24,
    borderWidth: 0,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    fontSize: typography.body,
    minHeight: 48,
  },
  sendBtn: {
    width: 46,
    height: 46,
    borderRadius: 23,
    justifyContent: 'center',
    alignItems: 'center',
  },
  quickActionCard: {
    borderRadius: 18,
  },
  quickActionSectionLabel: {
    fontSize: 10,
    fontWeight: '900',
    letterSpacing: 2,
    textTransform: 'uppercase',
    color: lightTheme.textMuted,
  },
  quickActionBody: {
    gap: spacing.sm,
  },
  quickActionTitle: {
    fontSize: typography.body,
    fontWeight: '800',
    color: lightTheme.textPrimary,
  },
  quickActionCopy: {
    fontSize: typography.bodySmall,
    color: lightTheme.textSecondary,
    lineHeight: 20,
  },
});
