import { SeedEventInvite } from './config';

/**
 * 55+ event invites across dating, workout, and mixed matches.
 *
 * Slug format: invite-{inviterSlug}-{inviteeSlug}-{eventSlug}
 * dayOffset is 0-10 days from seed baseline.
 */
export const seedEventInvites: SeedEventInvite[] = [
  // ── Existing invite (preserved) ──────────────────────────────────
  {
    slug: 'kai-invites-leilani-to-run',
    eventSlug: 'ala-moana-sunrise-run',
    matchSlug: 'kai-leilani',
    inviterSlug: 'kai',
    inviteeSlug: 'leilani',
    body: 'Want to make the chat real and join this one?',
    dayOffset: 0,
    hour: 12,
  },

  // ── kai-leilani (dating) ─────────────────────────────────────────
  {
    slug: 'invite-leilani-kai-diamond-head-power-hike',
    eventSlug: 'diamond-head-power-hike',
    matchSlug: 'kai-leilani',
    inviterSlug: 'leilani',
    inviteeSlug: 'kai',
    body: 'Sunset hike with a view? You in?',
    dayOffset: 0,
    hour: 14,
  },
  {
    slug: 'invite-kai-leilani-kapahulu-volleyball-social',
    eventSlug: 'kapahulu-volleyball-social',
    matchSlug: 'kai-leilani',
    inviterSlug: 'kai',
    inviteeSlug: 'leilani',
    body: 'Beach volleyball Saturday\u2014rotating teams, super chill.',
    dayOffset: 3,
    hour: 10,
  },
  {
    slug: 'invite-kai-leilani-kapolei-endurance-club',
    eventSlug: 'kapolei-endurance-club',
    matchSlug: 'kai-leilani',
    inviterSlug: 'kai',
    inviteeSlug: 'leilani',
    body: 'Tempo run into a recovery swim. Thought of you immediately.',
    dayOffset: 8,
    hour: 9,
  },

  // ── jordan-tessa (dating) ────────────────────────────────────────
  {
    slug: 'invite-jordan-tessa-kaimuki-boxing-circuit',
    eventSlug: 'kaimuki-boxing-circuit',
    matchSlug: 'jordan-tessa',
    inviterSlug: 'jordan',
    inviteeSlug: 'tessa',
    body: 'I\'m running boxing circuit night. Beginner lane if you need it.',
    dayOffset: 1,
    hour: 11,
  },
  {
    slug: 'invite-tessa-jordan-kapahulu-volleyball-social',
    eventSlug: 'kapahulu-volleyball-social',
    matchSlug: 'jordan-tessa',
    inviterSlug: 'tessa',
    inviteeSlug: 'jordan',
    body: 'I\'m hosting this one. Drop-in teams, no one takes it too seriously.',
    dayOffset: 3,
    hour: 9,
  },
  {
    slug: 'invite-jordan-tessa-north-shore-surf-morning',
    eventSlug: 'north-shore-surf-morning',
    matchSlug: 'jordan-tessa',
    inviterSlug: 'jordan',
    inviteeSlug: 'tessa',
    body: 'Carpool up for waves? Poke after if the morning\'s good.',
    dayOffset: 8,
    hour: 20,
  },

  // ── nia-keoni (dating) ───────────────────────────────────────────
  {
    slug: 'invite-nia-keoni-diamond-head-power-hike',
    eventSlug: 'diamond-head-power-hike',
    matchSlug: 'nia-keoni',
    inviterSlug: 'nia',
    inviteeSlug: 'keoni',
    body: 'I\'m hosting this one\u2014would be cool to finally hike together.',
    dayOffset: 0,
    hour: 11,
  },
  {
    slug: 'invite-keoni-nia-makapuu-first-light',
    eventSlug: 'makapuu-first-light',
    matchSlug: 'nia-keoni',
    inviterSlug: 'keoni',
    inviteeSlug: 'nia',
    body: 'Sunrise hike and maybe whale spotting? Worth the early alarm.',
    dayOffset: 4,
    hour: 19,
  },
  {
    slug: 'invite-nia-keoni-manoa-reset-walk',
    eventSlug: 'manoa-reset-walk',
    matchSlug: 'nia-keoni',
    inviterSlug: 'nia',
    inviteeSlug: 'keoni',
    body: 'Low-key walk to decompress\u2014no pressure, just fresh air.',
    dayOffset: 9,
    hour: 12,
  },

  // ── sasha-eli (dating) ───────────────────────────────────────────
  {
    slug: 'invite-sasha-eli-mccully-dance-night',
    eventSlug: 'mccully-dance-night',
    matchSlug: 'sasha-eli',
    inviterSlug: 'sasha',
    inviteeSlug: 'eli',
    body: 'Dance cardio and mocktails after. Better with company.',
    dayOffset: 4,
    hour: 13,
  },
  {
    slug: 'invite-eli-sasha-pearl-city-long-ride',
    eventSlug: 'pearl-city-long-ride',
    matchSlug: 'sasha-eli',
    inviterSlug: 'eli',
    inviteeSlug: 'sasha',
    body: 'I\'m leading a 25-miler with regroup points. Cafe stop mid-ride.',
    dayOffset: 5,
    hour: 17,
  },
  {
    slug: 'invite-sasha-eli-kakaako-pilates-brunch',
    eventSlug: 'kakaako-pilates-brunch',
    matchSlug: 'sasha-eli',
    inviterSlug: 'sasha',
    inviteeSlug: 'eli',
    body: 'Pilates then brunch with whoever stays. Could be a fun hangout.',
    dayOffset: 5,
    hour: 15,
  },

  // ── alana-devon (dating) ─────────────────────────────────────────
  {
    slug: 'invite-alana-devon-kaneohe-climb-night',
    eventSlug: 'kaneohe-climb-night',
    matchSlug: 'alana-devon',
    inviterSlug: 'alana',
    inviteeSlug: 'devon',
    body: 'Saw this event and thought of you. Climbing night\u2014interested?',
    dayOffset: 6,
    hour: 15,
  },
  {
    slug: 'invite-devon-alana-manoa-reset-walk',
    eventSlug: 'manoa-reset-walk',
    matchSlug: 'alana-devon',
    inviterSlug: 'devon',
    inviteeSlug: 'alana',
    body: 'Recovery walk through Manoa. Fresh air and normal conversation.',
    dayOffset: 9,
    hour: 8,
  },
  {
    slug: 'invite-alana-devon-kaimana-beach-sunrise-yoga',
    eventSlug: 'kaimana-beach-sunrise-yoga',
    matchSlug: 'alana-devon',
    inviterSlug: 'alana',
    inviteeSlug: 'devon',
    body: 'Beach yoga at sunrise\u2014mellow start before the day gets busy.',
    dayOffset: 2,
    hour: 8,
  },

  // ── cole-malia (dating) ──────────────────────────────────────────
  {
    slug: 'invite-cole-malia-north-shore-surf-morning',
    eventSlug: 'north-shore-surf-morning',
    matchSlug: 'cole-malia',
    inviterSlug: 'cole',
    inviteeSlug: 'malia',
    body: 'I\'m hosting a carpool up for waves. Split poke after?',
    dayOffset: 8,
    hour: 14,
  },
  {
    slug: 'invite-malia-cole-kailua-paddle-social',
    eventSlug: 'kailua-paddle-social',
    matchSlug: 'cole-malia',
    inviterSlug: 'malia',
    inviteeSlug: 'cole',
    body: 'Hosting a paddle session\u2014breakfast burritos after. You free?',
    dayOffset: 1,
    hour: 18,
  },
  {
    slug: 'invite-cole-malia-kapahulu-volleyball-social',
    eventSlug: 'kapahulu-volleyball-social',
    matchSlug: 'cole-malia',
    inviterSlug: 'cole',
    inviteeSlug: 'malia',
    body: 'Rotating teams at the park. Good crew, easygoing rules.',
    dayOffset: 6,
    hour: 10,
  },

  // ── priya-luca (dating) ──────────────────────────────────────────
  {
    slug: 'invite-priya-luca-downtown-strength-hour',
    eventSlug: 'downtown-strength-hour',
    matchSlug: 'priya-luca',
    inviterSlug: 'priya',
    inviteeSlug: 'luca',
    body: 'Squat emphasis, simple accessories. No influencer energy.',
    dayOffset: 2,
    hour: 10,
  },
  {
    slug: 'invite-luca-priya-ala-moana-friends-lift',
    eventSlug: 'ala-moana-friends-lift',
    matchSlug: 'priya-luca',
    inviterSlug: 'luca',
    inviteeSlug: 'priya',
    body: 'Partner sets and mobility finisher. Bring a towel.',
    dayOffset: 10,
    hour: 13,
  },
  {
    slug: 'invite-priya-luca-kaimuki-boxing-circuit',
    eventSlug: 'kaimuki-boxing-circuit',
    matchSlug: 'priya-luca',
    inviterSlug: 'priya',
    inviteeSlug: 'luca',
    body: 'I\'m hosting combat conditioning. Intense but well-coached.',
    dayOffset: 7,
    hour: 12,
  },

  // ── maren-rafael (dating) ────────────────────────────────────────
  {
    slug: 'invite-maren-rafael-kapolei-endurance-club',
    eventSlug: 'kapolei-endurance-club',
    matchSlug: 'maren-rafael',
    inviterSlug: 'maren',
    inviteeSlug: 'rafael',
    body: 'I\'m hosting endurance club\u2014tempo run then a recovery swim.',
    dayOffset: 8,
    hour: 16,
  },
  {
    slug: 'invite-rafael-maren-waikiki-swim-laps',
    eventSlug: 'waikiki-swim-laps',
    matchSlug: 'maren-rafael',
    inviterSlug: 'rafael',
    inviteeSlug: 'maren',
    body: 'Open water swim and shave ice walk. If you\'re around Thursday.',
    dayOffset: 2,
    hour: 14,
  },
  {
    slug: 'invite-maren-rafael-ala-moana-sunrise-run',
    eventSlug: 'ala-moana-sunrise-run',
    matchSlug: 'maren-rafael',
    inviterSlug: 'maren',
    inviteeSlug: 'rafael',
    body: 'Sunrise boardwalk miles and smoothies. Easy way to start the day.',
    dayOffset: 0,
    hour: 18,
  },

  // ── eli-june (dating) ────────────────────────────────────────────
  {
    slug: 'invite-eli-june-pearl-city-long-ride',
    eventSlug: 'pearl-city-long-ride',
    matchSlug: 'eli-june',
    inviterSlug: 'eli',
    inviteeSlug: 'june',
    body: 'Rolling hills Saturday. Nobody gets dropped\u2014promise.',
    dayOffset: 7,
    hour: 10,
  },
  {
    slug: 'invite-june-eli-diamond-head-tempo-loop',
    eventSlug: 'diamond-head-tempo-loop',
    matchSlug: 'eli-june',
    inviterSlug: 'june',
    inviteeSlug: 'eli',
    body: 'Tempo loop around Diamond Head. Meet at the trailhead?',
    dayOffset: 3,
    hour: 16,
  },

  // ── keoni-isla (dating) ──────────────────────────────────────────
  {
    slug: 'invite-keoni-isla-kailua-paddle-social',
    eventSlug: 'kailua-paddle-social',
    matchSlug: 'keoni-isla',
    inviterSlug: 'keoni',
    inviteeSlug: 'isla',
    body: 'Paddle and breakfast at Kailua. If you\'re around Saturday.',
    dayOffset: 1,
    hour: 10,
  },
  {
    slug: 'invite-isla-keoni-kaimana-beach-sunrise-yoga',
    eventSlug: 'kaimana-beach-sunrise-yoga',
    matchSlug: 'keoni-isla',
    inviterSlug: 'isla',
    inviteeSlug: 'keoni',
    body: 'Sunrise yoga on the sand\u2014super mellow, perfect if you\'re free.',
    dayOffset: 0,
    hour: 9,
  },

  // ── devon-hazel (dating) ─────────────────────────────────────────
  {
    slug: 'invite-devon-hazel-kaneohe-climb-night',
    eventSlug: 'kaneohe-climb-night',
    matchSlug: 'devon-hazel',
    inviterSlug: 'devon',
    inviteeSlug: 'hazel',
    body: 'Climbing night at Kaneohe. Strength finisher after.',
    dayOffset: 3,
    hour: 12,
  },
  {
    slug: 'invite-hazel-devon-kakaako-pilates-brunch',
    eventSlug: 'kakaako-pilates-brunch',
    matchSlug: 'devon-hazel',
    inviterSlug: 'hazel',
    inviteeSlug: 'devon',
    body: 'Pilates then brunch. Basically the perfect Saturday.',
    dayOffset: 10,
    hour: 18,
  },

  // ── tessa-noa (dating) ───────────────────────────────────────────
  {
    slug: 'invite-tessa-noa-mccully-dance-night',
    eventSlug: 'mccully-dance-night',
    matchSlug: 'tessa-noa',
    inviterSlug: 'tessa',
    inviteeSlug: 'noa',
    body: 'Dance cardio then mocktails. Was just about to RSVP\u2014come with?',
    dayOffset: 4,
    hour: 9,
  },
  {
    slug: 'invite-noa-tessa-lanikai-pillbox-sunrise',
    eventSlug: 'lanikai-pillbox-sunrise',
    matchSlug: 'tessa-noa',
    inviterSlug: 'noa',
    inviteeSlug: 'tessa',
    body: 'Pillbox at sunrise\u2014the view is unreal. Worth the early wake-up.',
    dayOffset: 1,
    hour: 19,
  },

  // ── jordan-malia (dating) ────────────────────────────────────────
  {
    slug: 'invite-jordan-malia-koko-head-stairs-challenge',
    eventSlug: 'koko-head-stairs-challenge',
    matchSlug: 'jordan-malia',
    inviterSlug: 'jordan',
    inviteeSlug: 'malia',
    body: 'Koko Head stairs at dawn. It\'s brutal but the views are worth it.',
    dayOffset: 2,
    hour: 8,
  },
  {
    slug: 'invite-malia-jordan-waikiki-swim-laps',
    eventSlug: 'waikiki-swim-laps',
    matchSlug: 'jordan-malia',
    inviterSlug: 'malia',
    inviteeSlug: 'jordan',
    body: 'Open water laps then acai. Super chill vibe.',
    dayOffset: 5,
    hour: 11,
  },

  // ── nia-cole (dating) ────────────────────────────────────────────
  {
    slug: 'invite-nia-cole-kapiolani-park-track-night',
    eventSlug: 'kapiolani-park-track-night',
    matchSlug: 'nia-cole',
    inviterSlug: 'nia',
    inviteeSlug: 'cole',
    body: 'Track night at Kapiolani. Mixed paces, good group energy.',
    dayOffset: 5,
    hour: 17,
  },
  {
    slug: 'invite-cole-nia-north-shore-surf-morning',
    eventSlug: 'north-shore-surf-morning',
    matchSlug: 'nia-cole',
    inviterSlug: 'cole',
    inviteeSlug: 'nia',
    body: 'Carpool up for some waves? I know a good poke spot after.',
    dayOffset: 8,
    hour: 17,
  },

  // ── mason-nora (dating) ──────────────────────────────────────────
  {
    slug: 'invite-mason-nora-downtown-strength-hour',
    eventSlug: 'downtown-strength-hour',
    matchSlug: 'mason-nora',
    inviterSlug: 'mason',
    inviteeSlug: 'nora',
    body: 'Strength hour downtown. Good programming, small group.',
    dayOffset: 2,
    hour: 15,
  },
  {
    slug: 'invite-nora-mason-ala-moana-friends-lift',
    eventSlug: 'ala-moana-friends-lift',
    matchSlug: 'mason-nora',
    inviterSlug: 'nora',
    inviteeSlug: 'mason',
    body: 'Compact lift with a real mobility finish. You\'ll thank me after.',
    dayOffset: 7,
    hour: 14,
  },

  // ── leilani-finn (dating) ────────────────────────────────────────
  {
    slug: 'invite-leilani-finn-kaimana-beach-sunrise-yoga',
    eventSlug: 'kaimana-beach-sunrise-yoga',
    matchSlug: 'leilani-finn',
    inviterSlug: 'leilani',
    inviteeSlug: 'finn',
    body: 'Beach yoga at Kaimana\u2014tea and intros on the sand after.',
    dayOffset: 0,
    hour: 9,
  },
  {
    slug: 'invite-finn-leilani-kailua-paddle-social',
    eventSlug: 'kailua-paddle-social',
    matchSlug: 'leilani-finn',
    inviterSlug: 'finn',
    inviteeSlug: 'leilani',
    body: 'Steady paddle laps at the bay. Optional ocean dip after.',
    dayOffset: 9,
    hour: 19,
  },

  // ── kai-hana (dating) ────────────────────────────────────────────
  {
    slug: 'invite-kai-hana-makapuu-first-light',
    eventSlug: 'makapuu-first-light',
    matchSlug: 'kai-hana',
    inviterSlug: 'kai',
    inviteeSlug: 'hana',
    body: 'Perfect excuse to finally do that hike you mentioned.',
    dayOffset: 4,
    hour: 18,
  },
  {
    slug: 'invite-hana-kai-ala-moana-sunrise-run',
    eventSlug: 'ala-moana-sunrise-run',
    matchSlug: 'kai-hana',
    inviterSlug: 'hana',
    inviteeSlug: 'kai',
    body: 'Hosting the sunrise run\u2014coffee at the end. Come through.',
    dayOffset: 0,
    hour: 8,
  },

  // ── wo-kai-akira (workout) ───────────────────────────────────────
  {
    slug: 'invite-kai-akira-diamond-head-power-hike',
    eventSlug: 'diamond-head-power-hike',
    matchSlug: 'wo-kai-akira',
    inviterSlug: 'kai',
    inviteeSlug: 'akira',
    body: 'Power hike with a good crew. Solid cardio and the view\'s a bonus.',
    dayOffset: 1,
    hour: 14,
  },
  {
    slug: 'invite-akira-kai-koko-head-stairs-challenge',
    eventSlug: 'koko-head-stairs-challenge',
    matchSlug: 'wo-kai-akira',
    inviterSlug: 'akira',
    inviteeSlug: 'kai',
    body: 'Koko Head stairs challenge\u2014timed repeats. You game?',
    dayOffset: 6,
    hour: 8,
  },

  // ── wo-mason-kenji (workout) ─────────────────────────────────────
  {
    slug: 'invite-mason-kenji-downtown-strength-hour',
    eventSlug: 'downtown-strength-hour',
    matchSlug: 'wo-mason-kenji',
    inviterSlug: 'mason',
    inviteeSlug: 'kenji',
    body: 'Squat emphasis, simple accessories. No influencer energy.',
    dayOffset: 2,
    hour: 10,
  },
  {
    slug: 'invite-kenji-mason-ala-moana-friends-lift',
    eventSlug: 'ala-moana-friends-lift',
    matchSlug: 'wo-mason-kenji',
    inviterSlug: 'kenji',
    inviteeSlug: 'mason',
    body: 'Partner sets and mobility finisher. I\'m hosting\u2014bring a towel.',
    dayOffset: 10,
    hour: 13,
  },

  // ── wo-jordan-sora (workout) ─────────────────────────────────────
  {
    slug: 'invite-jordan-sora-kaimuki-boxing-circuit',
    eventSlug: 'kaimuki-boxing-circuit',
    matchSlug: 'wo-jordan-sora',
    inviterSlug: 'jordan',
    inviteeSlug: 'sora',
    body: 'Boxing circuit night. Glove work, bag intervals\u2014you\'d fit right in.',
    dayOffset: 1,
    hour: 15,
  },
  {
    slug: 'invite-sora-jordan-kapiolani-park-track-night',
    eventSlug: 'kapiolani-park-track-night',
    matchSlug: 'wo-jordan-sora',
    inviterSlug: 'sora',
    inviteeSlug: 'jordan',
    body: 'Track intervals under the lights. Mixed paces, no judgment.',
    dayOffset: 5,
    hour: 18,
  },

  // ── wo-rowan-taro (workout) ──────────────────────────────────────
  {
    slug: 'invite-rowan-taro-downtown-strength-hour',
    eventSlug: 'downtown-strength-hour',
    matchSlug: 'wo-rowan-taro',
    inviterSlug: 'rowan',
    inviteeSlug: 'taro',
    body: 'Strength hour downtown. Good programming, small group.',
    dayOffset: 3,
    hour: 15,
  },
  {
    slug: 'invite-taro-rowan-koko-head-stairs-challenge',
    eventSlug: 'koko-head-stairs-challenge',
    matchSlug: 'wo-rowan-taro',
    inviterSlug: 'taro',
    inviteeSlug: 'rowan',
    body: 'Stair repeats then stretch. Brutal but satisfying.',
    dayOffset: 7,
    hour: 8,
  },

  // ── wo-eli-mei (workout) ─────────────────────────────────────────
  {
    slug: 'invite-eli-mei-pearl-city-long-ride',
    eventSlug: 'pearl-city-long-ride',
    matchSlug: 'wo-eli-mei',
    inviterSlug: 'eli',
    inviteeSlug: 'mei',
    body: 'I\'m leading a long ride\u2014cafe stop built in. Want to join?',
    dayOffset: 5,
    hour: 16,
  },
  {
    slug: 'invite-mei-eli-diamond-head-tempo-loop',
    eventSlug: 'diamond-head-tempo-loop',
    matchSlug: 'wo-eli-mei',
    inviterSlug: 'mei',
    inviteeSlug: 'eli',
    body: 'Diamond Head tempo loop. Perfect mid-week effort.',
    dayOffset: 4,
    hour: 11,
  },

  // ── wo-priya-koa (workout) ───────────────────────────────────────
  {
    slug: 'invite-priya-koa-kaimuki-boxing-circuit',
    eventSlug: 'kaimuki-boxing-circuit',
    matchSlug: 'wo-priya-koa',
    inviterSlug: 'priya',
    inviteeSlug: 'koa',
    body: 'Fast circuits and mitt rounds. Good coaching at this one.',
    dayOffset: 7,
    hour: 11,
  },
  {
    slug: 'invite-koa-priya-kapolei-endurance-club',
    eventSlug: 'kapolei-endurance-club',
    matchSlug: 'wo-priya-koa',
    inviterSlug: 'koa',
    inviteeSlug: 'priya',
    body: 'West side endurance club. Run and swim\u2014right up your alley.',
    dayOffset: 8,
    hour: 11,
  },

  // ── wo-cole-lani (workout) ───────────────────────────────────────
  {
    slug: 'invite-cole-lani-north-shore-surf-morning',
    eventSlug: 'north-shore-surf-morning',
    matchSlug: 'wo-cole-lani',
    inviterSlug: 'cole',
    inviteeSlug: 'lani',
    body: 'North Shore morning surf. I\'ll drive if you bring snacks.',
    dayOffset: 6,
    hour: 8,
  },
  {
    slug: 'invite-lani-cole-waikiki-swim-laps',
    eventSlug: 'waikiki-swim-laps',
    matchSlug: 'wo-cole-lani',
    inviterSlug: 'lani',
    inviteeSlug: 'cole',
    body: 'Open water laps at Waikiki. No rush, mixed speeds welcome.',
    dayOffset: 4,
    hour: 13,
  },

  // ── wo-maren-makoa (workout) ─────────────────────────────────────
  {
    slug: 'invite-maren-makoa-kapolei-endurance-club',
    eventSlug: 'kapolei-endurance-club',
    matchSlug: 'wo-maren-makoa',
    inviterSlug: 'maren',
    inviteeSlug: 'makoa',
    body: 'Endurance club out west. Tempo run plus a recovery swim.',
    dayOffset: 9,
    hour: 9,
  },
  {
    slug: 'invite-makoa-maren-ala-moana-sunrise-run',
    eventSlug: 'ala-moana-sunrise-run',
    matchSlug: 'wo-maren-makoa',
    inviterSlug: 'makoa',
    inviteeSlug: 'maren',
    body: 'Sunrise miles at Ala Moana. Coffee and catch-up after.',
    dayOffset: 1,
    hour: 8,
  },

  // ── mx-akira-leilani (mixed) ─────────────────────────────────────
  {
    slug: 'invite-akira-leilani-kakaako-pilates-brunch',
    eventSlug: 'kakaako-pilates-brunch',
    matchSlug: 'mx-akira-leilani',
    inviterSlug: 'akira',
    inviteeSlug: 'leilani',
    body: 'Golden hour pilates and brunch\u2014tea on the deck after class.',
    dayOffset: 0,
    hour: 10,
  },
  {
    slug: 'invite-leilani-akira-lanikai-pillbox-sunrise',
    eventSlug: 'lanikai-pillbox-sunrise',
    matchSlug: 'mx-akira-leilani',
    inviterSlug: 'leilani',
    inviteeSlug: 'akira',
    body: 'Pillbox hike at first light. The colors are incredible.',
    dayOffset: 3,
    hour: 19,
  },

  // ── mx-hana-jordan (mixed) ───────────────────────────────────────
  {
    slug: 'invite-hana-jordan-kaimana-beach-sunrise-yoga',
    eventSlug: 'kaimana-beach-sunrise-yoga',
    matchSlug: 'mx-hana-jordan',
    inviterSlug: 'hana',
    inviteeSlug: 'jordan',
    body: 'Beach yoga at Kaimana. Low-key and grounding.',
    dayOffset: 2,
    hour: 8,
  },
  {
    slug: 'invite-jordan-hana-diamond-head-power-hike',
    eventSlug: 'diamond-head-power-hike',
    matchSlug: 'mx-hana-jordan',
    inviterSlug: 'jordan',
    inviteeSlug: 'hana',
    body: 'Power hike\u2014solid effort and the summit view makes it worth it.',
    dayOffset: 5,
    hour: 14,
  },

  // ── mx-sora-tessa (mixed) ────────────────────────────────────────
  {
    slug: 'invite-sora-tessa-kapahulu-volleyball-social',
    eventSlug: 'kapahulu-volleyball-social',
    matchSlug: 'mx-sora-tessa',
    inviterSlug: 'sora',
    inviteeSlug: 'tessa',
    body: 'Beach volleyball at Kapiolani. Rotating teams, zero pressure.',
    dayOffset: 3,
    hour: 11,
  },
  {
    slug: 'invite-tessa-sora-mccully-dance-night',
    eventSlug: 'mccully-dance-night',
    matchSlug: 'mx-sora-tessa',
    inviterSlug: 'tessa',
    inviteeSlug: 'sora',
    body: 'Dance night\u2014the music is great and nobody cares if you\'re good.',
    dayOffset: 6,
    hour: 19,
  },

  // ── mx-yuki-nia (mixed) ──────────────────────────────────────────
  {
    slug: 'invite-yuki-nia-makapuu-first-light',
    eventSlug: 'makapuu-first-light',
    matchSlug: 'mx-yuki-nia',
    inviterSlug: 'yuki',
    inviteeSlug: 'nia',
    body: 'Makapuu at first light. Bring a camera\u2014the sunrise is surreal.',
    dayOffset: 4,
    hour: 8,
  },
  {
    slug: 'invite-nia-yuki-manoa-reset-walk',
    eventSlug: 'manoa-reset-walk',
    matchSlug: 'mx-yuki-nia',
    inviterSlug: 'nia',
    inviteeSlug: 'yuki',
    body: 'Manoa walk for a midweek reset. Just fresh air and good company.',
    dayOffset: 7,
    hour: 12,
  },

  // ── mx-kai-riko (mixed) ──────────────────────────────────────────
  {
    slug: 'invite-kai-riko-ala-moana-sunrise-run',
    eventSlug: 'ala-moana-sunrise-run',
    matchSlug: 'mx-kai-riko',
    inviterSlug: 'kai',
    inviteeSlug: 'riko',
    body: 'Sunrise run at Ala Moana\u2014I\'ll pace us. Coffee on me after.',
    dayOffset: 0,
    hour: 8,
  },
  {
    slug: 'invite-riko-kai-koko-head-stairs-challenge',
    eventSlug: 'koko-head-stairs-challenge',
    matchSlug: 'mx-kai-riko',
    inviterSlug: 'riko',
    inviteeSlug: 'kai',
    body: 'Koko Head stairs\u2014timed reps or just enjoy the climb. Your call.',
    dayOffset: 6,
    hour: 9,
  },

  // ── mx-cole-koa (mixed) ──────────────────────────────────────────
  {
    slug: 'invite-cole-koa-north-shore-surf-morning',
    eventSlug: 'north-shore-surf-morning',
    matchSlug: 'mx-cole-koa',
    inviterSlug: 'cole',
    inviteeSlug: 'koa',
    body: 'Mellow longboard session on the North Shore. Sunlight and snacks.',
    dayOffset: 8,
    hour: 19,
  },
  {
    slug: 'invite-koa-cole-kailua-paddle-social',
    eventSlug: 'kailua-paddle-social',
    matchSlug: 'mx-cole-koa',
    inviterSlug: 'koa',
    inviteeSlug: 'cole',
    body: 'Harbor paddle\u2014steady pace. Good for a workout without the chaos.',
    dayOffset: 6,
    hour: 20,
  },
];
