import { SeedMatch } from './config';

/**
 * 30 mixed matches (isDatingMatch + isWorkoutMatch).
 * These represent the deepest connections - people who clicked on both levels.
 *
 * Distribution:
 *   5 matches  x  0-2 messages  (fresh)
 *  10 matches  x  3-6 messages
 *  10 matches  x  7-12 messages
 *   5 matches  x 13-18 messages (deepest convos)
 *
 * Special flags: 3 archived, 1 blocked
 */
export const mixedMatches: SeedMatch[] = [
  // ─────────────────────────────────────────────────────────────────
  // TIER 1 — Fresh (0-2 messages)  [5 matches]
  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'mx-akira-leilani',
    userSlugs: ['akira', 'leilani'],
    dayOffset: 0,
    hour: 9,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [],
  },
  {
    slug: 'mx-hana-jordan',
    userSlugs: ['hana', 'jordan'],
    dayOffset: 0,
    hour: 14,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'mx-hana-jordan-msg-1',
        senderSlug: 'hana',
        body: 'Hey! I saw we matched on both dating and workout - that never happens. What do you usually train?',
        hoursAfterMatch: 1,
        isRead: true,
      },
    ],
  },
  {
    slug: 'mx-kenji-malia',
    userSlugs: ['kenji', 'malia'],
    dayOffset: 1,
    hour: 7,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'mx-kenji-malia-msg-1',
        senderSlug: 'malia',
        body: 'A surfer who also does yoga? Ok I am intrigued',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'mx-kenji-malia-msg-2',
        senderSlug: 'kenji',
        body: 'Ha - guilty as charged. Sunrise sessions at Ala Moana are my thing. You should come sometime!',
        hoursAfterMatch: 3,
      },
    ],
  },
  {
    slug: 'mx-sora-tessa',
    userSlugs: ['sora', 'tessa'],
    dayOffset: 1,
    hour: 18,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'mx-sora-tessa-msg-1',
        senderSlug: 'tessa',
        body: 'Dual match! Guess the algorithm knows something we don\'t yet',
        hoursAfterMatch: 0.5,
      },
    ],
  },
  {
    slug: 'mx-yuki-nia',
    userSlugs: ['yuki', 'nia'],
    dayOffset: 2,
    hour: 11,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [],
  },

  // ─────────────────────────────────────────────────────────────────
  // TIER 2 — Building (3-6 messages)  [10 matches]
  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'mx-kai-riko',
    userSlugs: ['kai', 'riko'],
    dayOffset: 2,
    hour: 8,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'mx-kai-riko-msg-1',
        senderSlug: 'kai',
        body: 'Both dating AND workout match - I feel like we already have a head start',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'mx-kai-riko-msg-2',
        senderSlug: 'riko',
        body: 'Right?? So what is your go-to workout? I have been obsessed with climbing lately',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'mx-kai-riko-msg-3',
        senderSlug: 'kai',
        body: 'No way - I just started bouldering at the Volcanic Rock Gym. We should session together',
        hoursAfterMatch: 3,
        isRead: true,
      },
    ],
  },
  {
    slug: 'mx-rowan-aiko',
    userSlugs: ['rowan', 'aiko'],
    dayOffset: 3,
    hour: 10,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'mx-rowan-aiko-msg-1',
        senderSlug: 'aiko',
        body: 'Your profile says you run the Diamond Head trail every weekend - that is commitment!',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'mx-rowan-aiko-msg-2',
        senderSlug: 'rowan',
        body: 'It is my church. Want to join this Saturday? I usually go at 6am before it gets crowded',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'mx-rowan-aiko-msg-3',
        senderSlug: 'aiko',
        body: '6am on a Saturday... you are really testing my interest level here',
        hoursAfterMatch: 4,
        isRead: true,
      },
      {
        slug: 'mx-rowan-aiko-msg-4',
        senderSlug: 'rowan',
        body: 'I will bring coffee. Good coffee. The kind that makes 6am feel like a choice, not a punishment',
        hoursAfterMatch: 5,
        isRead: true,
      },
    ],
  },
  {
    slug: 'mx-cole-koa',
    userSlugs: ['cole', 'koa'],
    dayOffset: 4,
    hour: 20,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'mx-cole-koa-msg-1',
        senderSlug: 'cole',
        body: 'Your paddling photos are incredible. How long have you been doing outrigger?',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'mx-cole-koa-msg-2',
        senderSlug: 'koa',
        body: 'Since I was 8 - family tradition. My grandpa raced in the Molokai Hoe back in the day',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'mx-cole-koa-msg-3',
        senderSlug: 'cole',
        body: 'That is amazing. I have always wanted to try but never knew where to start',
        hoursAfterMatch: 3,
        isRead: true,
      },
      {
        slug: 'mx-cole-koa-msg-4',
        senderSlug: 'koa',
        body: 'My club does intro sessions every Sunday at Kailua Beach. Come through - I will teach you the basics',
        hoursAfterMatch: 5,
      },
      {
        slug: 'mx-cole-koa-msg-5',
        senderSlug: 'cole',
        body: 'Deal. Fair warning though, my coordination on water is... questionable',
        hoursAfterMatch: 6,
      },
      {
        slug: 'mx-cole-koa-msg-6',
        senderSlug: 'koa',
        body: 'That is the best part - watching beginners fall in is half the fun. See you Sunday!',
        hoursAfterMatch: 7,
      },
    ],
  },
  {
    slug: 'mx-priya-jin',
    userSlugs: ['priya', 'jin'],
    dayOffset: 5,
    hour: 9,
    isDatingMatch: true,
    isWorkoutMatch: true,
    isArchived: true,
    messages: [
      {
        slug: 'mx-priya-jin-msg-1',
        senderSlug: 'jin',
        body: 'Hey! I see you are into strength training. What program are you running?',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'mx-priya-jin-msg-2',
        senderSlug: 'priya',
        body: 'Modified 5/3/1 right now. Getting close to a 200lb deadlift which is my big goal this year',
        hoursAfterMatch: 4,
        isRead: true,
      },
      {
        slug: 'mx-priya-jin-msg-3',
        senderSlug: 'jin',
        body: 'That is awesome. I am on GZCLP myself. We should compare notes sometime over coffee?',
        hoursAfterMatch: 6,
        isRead: true,
      },
    ],
  },
  {
    slug: 'mx-maren-lani',
    userSlugs: ['maren', 'lani'],
    dayOffset: 5,
    hour: 15,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'mx-maren-lani-msg-1',
        senderSlug: 'maren',
        body: 'Your bio mentioned you teach sunrise yoga on the beach? Where at?',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'mx-maren-lani-msg-2',
        senderSlug: 'lani',
        body: 'Waikiki near the Duke statue, Tuesdays and Thursdays at 5:45am. It is totally free - you should come!',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'mx-maren-lani-msg-3',
        senderSlug: 'maren',
        body: 'I am there. I have been wanting to get back into yoga but classes at studios are so expensive',
        hoursAfterMatch: 4,
        isRead: true,
      },
      {
        slug: 'mx-maren-lani-msg-4',
        senderSlug: 'lani',
        body: 'That is exactly why I started the free sessions. Yoga should be accessible to everyone. And the ocean backdrop is better than any studio anyway',
        hoursAfterMatch: 5,
      },
      {
        slug: 'mx-maren-lani-msg-5',
        senderSlug: 'maren',
        body: 'Could not agree more. See you Tuesday morning - I will be the one looking completely lost in downward dog',
        hoursAfterMatch: 6,
      },
    ],
  },
  {
    slug: 'mx-sasha-makoa',
    userSlugs: ['sasha', 'makoa'],
    dayOffset: 6,
    hour: 11,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'mx-sasha-makoa-msg-1',
        senderSlug: 'sasha',
        body: 'Ok your volleyball photos are FIRE. Do you play at Queen\'s Beach?',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'mx-sasha-makoa-msg-2',
        senderSlug: 'makoa',
        body: 'Every Saturday and Sunday! We have a regular crew but always welcome new people. You play?',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'mx-sasha-makoa-msg-3',
        senderSlug: 'sasha',
        body: 'Played in college actually. Been looking for pickup games since I moved here',
        hoursAfterMatch: 3,
        isRead: true,
      },
      {
        slug: 'mx-sasha-makoa-msg-4',
        senderSlug: 'makoa',
        body: 'College player?? You are definitely on my team then. Saturday 10am, court closest to the lifeguard tower',
        hoursAfterMatch: 4,
      },
    ],
  },
  {
    slug: 'mx-noa-alana',
    userSlugs: ['noa', 'alana'],
    dayOffset: 6,
    hour: 19,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'mx-noa-alana-msg-1',
        senderSlug: 'alana',
        body: 'A fellow hiker! Have you done the Koko Head stairs yet?',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'mx-noa-alana-msg-2',
        senderSlug: 'noa',
        body: 'Three times! Still recovering emotionally from the first attempt though. Those stairs are no joke',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'mx-noa-alana-msg-3',
        senderSlug: 'alana',
        body: 'Haha I remember my first time - my legs were shaking so bad I had to sit at the top for 20 minutes',
        hoursAfterMatch: 3,
        isRead: true,
      },
      {
        slug: 'mx-noa-alana-msg-4',
        senderSlug: 'noa',
        body: 'Want to do it together this weekend? Misery loves company and all that',
        hoursAfterMatch: 5,
      },
      {
        slug: 'mx-noa-alana-msg-5',
        senderSlug: 'alana',
        body: 'Yes! And there is an amazing loco moco spot at the bottom we can hit after as a reward',
        hoursAfterMatch: 6,
      },
    ],
  },
  {
    slug: 'mx-cameron-keala',
    userSlugs: ['cameron', 'keala'],
    dayOffset: 7,
    hour: 8,
    isDatingMatch: true,
    isWorkoutMatch: true,
    isArchived: true,
    messages: [
      {
        slug: 'mx-cameron-keala-msg-1',
        senderSlug: 'cameron',
        body: 'Hey! Your swimming times are impressive. Do you compete?',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'mx-cameron-keala-msg-2',
        senderSlug: 'keala',
        body: 'Used to in high school. Now I just do it to stay sane. Open water mostly',
        hoursAfterMatch: 3,
        isRead: true,
      },
      {
        slug: 'mx-cameron-keala-msg-3',
        senderSlug: 'cameron',
        body: 'Open water is so much better than the pool. Where do you usually swim?',
        hoursAfterMatch: 5,
        isRead: true,
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // TIER 3 — Going deeper (7-12 messages)  [10 matches]
  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'mx-mason-nalani',
    userSlugs: ['mason', 'nalani'],
    dayOffset: 7,
    hour: 13,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'mx-mason-nalani-msg-1',
        senderSlug: 'mason',
        body: 'I cannot believe we matched on both - your profile is basically my fitness goals list',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'mx-mason-nalani-msg-2',
        senderSlug: 'nalani',
        body: 'Ha! Let me guess - you also want to do a triathlon before you turn 30?',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'mx-mason-nalani-msg-3',
        senderSlug: 'mason',
        body: 'How did you know?? I have been training for the Honolulu Tri in October actually',
        hoursAfterMatch: 3,
        isRead: true,
      },
      {
        slug: 'mx-mason-nalani-msg-4',
        senderSlug: 'nalani',
        body: 'Shut up, me too! I am doing the sprint distance though. What about you?',
        hoursAfterMatch: 4,
        isRead: true,
      },
      {
        slug: 'mx-mason-nalani-msg-5',
        senderSlug: 'mason',
        body: 'Olympic distance. The swim leg terrifies me though. My open water skills are... developing',
        hoursAfterMatch: 6,
        isRead: true,
      },
      {
        slug: 'mx-mason-nalani-msg-6',
        senderSlug: 'nalani',
        body: 'I am actually a really strong swimmer! We should train together. I will help with your swim if you pace me on the bike?',
        hoursAfterMatch: 8,
        isRead: true,
      },
      {
        slug: 'mx-mason-nalani-msg-7',
        senderSlug: 'mason',
        body: 'That is the best trade deal in the history of trade deals. Saturday morning at Ala Moana Beach Park?',
        hoursAfterMatch: 9,
        isRead: true,
      },
      {
        slug: 'mx-mason-nalani-msg-8',
        senderSlug: 'nalani',
        body: 'Done! And maybe breakfast after? I know a place with the best banana pancakes on the island',
        hoursAfterMatch: 10,
      },
    ],
  },
  {
    slug: 'mx-rafael-tessa',
    userSlugs: ['rafael', 'tessa'],
    dayOffset: 8,
    hour: 17,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'mx-rafael-tessa-msg-1',
        senderSlug: 'rafael',
        body: 'Your dance fitness classes look so fun! I have two left feet but I am curious',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'mx-rafael-tessa-msg-2',
        senderSlug: 'tessa',
        body: 'Everyone says that and then they end up loving it! It is more about having fun than being good',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'mx-rafael-tessa-msg-3',
        senderSlug: 'rafael',
        body: 'Ok you convinced me. When is the next one? I promise to embarrass myself with full commitment',
        hoursAfterMatch: 3,
        isRead: true,
      },
      {
        slug: 'mx-rafael-tessa-msg-4',
        senderSlug: 'tessa',
        body: 'Wednesday at 7pm at the community center in Kaimuki. And that is the best attitude to have honestly',
        hoursAfterMatch: 4,
        isRead: true,
      },
      {
        slug: 'mx-rafael-tessa-msg-5',
        senderSlug: 'rafael',
        body: 'I will be there. Also your profile says you like hiking - have you done the Lanikai Pillbox trail?',
        hoursAfterMatch: 6,
        isRead: true,
      },
      {
        slug: 'mx-rafael-tessa-msg-6',
        senderSlug: 'tessa',
        body: 'Only like 50 times! The sunrise from up there is unreal. We should go sometime',
        hoursAfterMatch: 7,
        isRead: true,
      },
      {
        slug: 'mx-rafael-tessa-msg-7',
        senderSlug: 'rafael',
        body: 'Dance class Wednesday, Pillbox hike Saturday sunrise? Are we already planning our whole week together?',
        hoursAfterMatch: 8,
      },
    ],
  },
  {
    slug: 'mx-ivy-rowan',
    userSlugs: ['ivy', 'rowan'],
    dayOffset: 9,
    hour: 10,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'mx-ivy-rowan-msg-1',
        senderSlug: 'ivy',
        body: 'Your climbing photos are insane! How long have you been at it?',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'mx-ivy-rowan-msg-2',
        senderSlug: 'rowan',
        body: 'About 3 years now. Started at the indoor gym and got totally hooked. Do you climb?',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'mx-ivy-rowan-msg-3',
        senderSlug: 'ivy',
        body: 'Just started bouldering! I am at V3 level and determined to hit V5 by year end',
        hoursAfterMatch: 3,
        isRead: true,
      },
      {
        slug: 'mx-ivy-rowan-msg-4',
        senderSlug: 'rowan',
        body: 'V3 to V5 is totally doable. It is all about technique over strength at that level',
        hoursAfterMatch: 4,
        isRead: true,
      },
      {
        slug: 'mx-ivy-rowan-msg-5',
        senderSlug: 'ivy',
        body: 'Would you want to session together sometime? I could use tips from someone more experienced',
        hoursAfterMatch: 6,
        isRead: true,
      },
      {
        slug: 'mx-ivy-rowan-msg-6',
        senderSlug: 'rowan',
        body: 'Absolutely! HiClimb on Thursday evenings is my regular spot. And then maybe dinner after?',
        hoursAfterMatch: 7,
        isRead: true,
      },
      {
        slug: 'mx-ivy-rowan-msg-7',
        senderSlug: 'ivy',
        body: 'Love that plan. There is a great poke place right next to HiClimb actually',
        hoursAfterMatch: 8,
        isRead: true,
      },
      {
        slug: 'mx-ivy-rowan-msg-8',
        senderSlug: 'rowan',
        body: 'Ono Poke? That is my favorite spot! Ok we officially have great taste in common',
        hoursAfterMatch: 9,
      },
      {
        slug: 'mx-ivy-rowan-msg-9',
        senderSlug: 'ivy',
        body: 'This Thursday then? I will warn you - I get very competitive on the wall',
        hoursAfterMatch: 10,
      },
      {
        slug: 'mx-ivy-rowan-msg-10',
        senderSlug: 'rowan',
        body: 'Good. So do I. Loser buys the poke',
        hoursAfterMatch: 11,
      },
    ],
  },
  {
    slug: 'mx-beck-nia',
    userSlugs: ['beck', 'nia'],
    dayOffset: 9,
    hour: 20,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'mx-beck-nia-msg-1',
        senderSlug: 'beck',
        body: 'Fellow pilates enthusiast! Reformer or mat?',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'mx-beck-nia-msg-2',
        senderSlug: 'nia',
        body: 'Reformer all day. There is something so satisfying about that spring resistance',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'mx-beck-nia-msg-3',
        senderSlug: 'beck',
        body: 'Same! Do you go to CorePower in Kakaako? Their reformer classes are amazing',
        hoursAfterMatch: 3,
        isRead: true,
      },
      {
        slug: 'mx-beck-nia-msg-4',
        senderSlug: 'nia',
        body: 'That is literally my studio! Monday and Wednesday mornings. This is getting spooky',
        hoursAfterMatch: 4,
        isRead: true,
      },
      {
        slug: 'mx-beck-nia-msg-5',
        senderSlug: 'beck',
        body: 'Ok the universe is clearly trying to tell us something. Coffee after class next Monday?',
        hoursAfterMatch: 6,
        isRead: true,
      },
      {
        slug: 'mx-beck-nia-msg-6',
        senderSlug: 'nia',
        body: 'Yes please! There is a new matcha place around the corner I have been wanting to try',
        hoursAfterMatch: 7,
        isRead: true,
      },
      {
        slug: 'mx-beck-nia-msg-7',
        senderSlug: 'beck',
        body: 'Matcha after pilates? You might be my dream human',
        hoursAfterMatch: 8,
      },
    ],
  },
  {
    slug: 'mx-june-mason',
    userSlugs: ['june', 'mason'],
    dayOffset: 10,
    hour: 8,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'mx-june-mason-msg-1',
        senderSlug: 'june',
        body: 'I see you are training for something - what is the goal?',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'mx-june-mason-msg-2',
        senderSlug: 'mason',
        body: 'Half marathon in April! First one ever. Terrified and excited in equal measures',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'mx-june-mason-msg-3',
        senderSlug: 'june',
        body: 'I did my first half last year! Best advice - do not go out too fast in the first mile',
        hoursAfterMatch: 3,
        isRead: true,
      },
      {
        slug: 'mx-june-mason-msg-4',
        senderSlug: 'mason',
        body: 'Noted! How do you train for it? I feel like I am just running aimlessly',
        hoursAfterMatch: 5,
        isRead: true,
      },
      {
        slug: 'mx-june-mason-msg-5',
        senderSlug: 'june',
        body: 'I followed the Hal Higdon plan - it is free online. Easy runs, tempo runs, long run on weekends. Changed everything for me',
        hoursAfterMatch: 6,
        isRead: true,
      },
      {
        slug: 'mx-june-mason-msg-6',
        senderSlug: 'mason',
        body: 'You are already a better coach than YouTube. Want to do a long run together this weekend?',
        hoursAfterMatch: 8,
        isRead: true,
      },
      {
        slug: 'mx-june-mason-msg-7',
        senderSlug: 'june',
        body: 'I would love that! I have a 10 mile route along the coast that is gorgeous. And flat-ish',
        hoursAfterMatch: 9,
        isRead: true,
      },
      {
        slug: 'mx-june-mason-msg-8',
        senderSlug: 'mason',
        body: 'Flat-ish is all I can ask for. What pace are you comfortable with?',
        hoursAfterMatch: 10,
        isRead: true,
      },
      {
        slug: 'mx-june-mason-msg-9',
        senderSlug: 'june',
        body: 'Around 9:30/mile for long runs. And there is a shave ice place at the turnaround point - mandatory stop',
        hoursAfterMatch: 11,
      },
      {
        slug: 'mx-june-mason-msg-10',
        senderSlug: 'mason',
        body: 'Shave ice at the halfway point might be the best running strategy I have ever heard',
        hoursAfterMatch: 12,
      },
    ],
  },
  {
    slug: 'mx-luca-maren',
    userSlugs: ['luca', 'maren'],
    dayOffset: 10,
    hour: 16,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'mx-luca-maren-msg-1',
        senderSlug: 'luca',
        body: 'Your mobility routine video on your profile is legit! Where did you learn all that?',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'mx-luca-maren-msg-2',
        senderSlug: 'maren',
        body: 'Years of physical therapy after a knee injury actually. Turned a negative into my whole fitness philosophy',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'mx-luca-maren-msg-3',
        senderSlug: 'luca',
        body: 'That is such a great mindset. I tore my ACL playing soccer and never really rehabbed properly',
        hoursAfterMatch: 3,
        isRead: true,
      },
      {
        slug: 'mx-luca-maren-msg-4',
        senderSlug: 'maren',
        body: 'Oh no! It is never too late to work on it. I could show you some of the exercises that helped me most',
        hoursAfterMatch: 4,
        isRead: true,
      },
      {
        slug: 'mx-luca-maren-msg-5',
        senderSlug: 'luca',
        body: 'I would really appreciate that. Where do you usually do your sessions?',
        hoursAfterMatch: 6,
        isRead: true,
      },
      {
        slug: 'mx-luca-maren-msg-6',
        senderSlug: 'maren',
        body: 'Kapiolani Park - there is a quiet spot by the banyan trees that is perfect for stretching',
        hoursAfterMatch: 7,
        isRead: true,
      },
      {
        slug: 'mx-luca-maren-msg-7',
        senderSlug: 'luca',
        body: 'That sounds peaceful. Could we meet there Sunday afternoon? I will bring smoothies',
        hoursAfterMatch: 9,
        isRead: true,
      },
      {
        slug: 'mx-luca-maren-msg-8',
        senderSlug: 'maren',
        body: 'Mobility work and smoothies under banyan trees? Best date idea I have heard on this app',
        hoursAfterMatch: 10,
      },
    ],
  },
  {
    slug: 'mx-arden-keoni',
    userSlugs: ['arden', 'keoni'],
    dayOffset: 11,
    hour: 9,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'mx-arden-keoni-msg-1',
        senderSlug: 'arden',
        body: 'I see you are into surfing AND strength training. That combo is chef kiss for paddling power',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'mx-arden-keoni-msg-2',
        senderSlug: 'keoni',
        body: 'Exactly! Most surfers neglect the gym but it makes such a difference out there',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'mx-arden-keoni-msg-3',
        senderSlug: 'arden',
        body: 'So what is your weekly split like? I am trying to balance surfing with lifting without overtraining',
        hoursAfterMatch: 3,
        isRead: true,
      },
      {
        slug: 'mx-arden-keoni-msg-4',
        senderSlug: 'keoni',
        body: 'Surf MWF mornings, lift TTh afternoons, active recovery on weekends. Took me a while to figure out the balance',
        hoursAfterMatch: 4,
        isRead: true,
      },
      {
        slug: 'mx-arden-keoni-msg-5',
        senderSlug: 'arden',
        body: 'That is really similar to what I want to do. Would you be down to lift together sometime? I could use a spotter',
        hoursAfterMatch: 6,
        isRead: true,
      },
      {
        slug: 'mx-arden-keoni-msg-6',
        senderSlug: 'keoni',
        body: 'Always need a good spotter! Thursday at Island Strength? 4pm?',
        hoursAfterMatch: 7,
        isRead: true,
      },
      {
        slug: 'mx-arden-keoni-msg-7',
        senderSlug: 'arden',
        body: 'Perfect. And if we vibe, maybe Friday morning surf session? I know a spot that is great for intermediates',
        hoursAfterMatch: 9,
        isRead: true,
      },
      {
        slug: 'mx-arden-keoni-msg-8',
        senderSlug: 'keoni',
        body: 'Already planning the second hangout before the first? I like your style',
        hoursAfterMatch: 10,
        isRead: true,
      },
      {
        slug: 'mx-arden-keoni-msg-9',
        senderSlug: 'arden',
        body: 'Life is short and waves do not wait. See you Thursday!',
        hoursAfterMatch: 11,
      },
    ],
  },
  {
    slug: 'mx-omar-leilani',
    userSlugs: ['omar', 'leilani'],
    dayOffset: 12,
    hour: 14,
    isDatingMatch: true,
    isWorkoutMatch: true,
    isBlocked: true,
    messages: [
      {
        slug: 'mx-omar-leilani-msg-1',
        senderSlug: 'omar',
        body: 'Hey! Looks like we both enjoy running. What distances do you usually do?',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'mx-omar-leilani-msg-2',
        senderSlug: 'leilani',
        body: '5K to 10K mostly. Working my way up to a half marathon eventually',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'mx-omar-leilani-msg-3',
        senderSlug: 'omar',
        body: 'Nice! I just ran my first half. It was tough but crossing that finish line was everything',
        hoursAfterMatch: 3,
        isRead: true,
      },
      {
        slug: 'mx-omar-leilani-msg-4',
        senderSlug: 'leilani',
        body: 'That is inspiring! Any tips for someone building up to it?',
        hoursAfterMatch: 5,
        isRead: true,
      },
      {
        slug: 'mx-omar-leilani-msg-5',
        senderSlug: 'omar',
        body: 'Consistency over intensity. And find a running buddy - it makes the long runs so much easier',
        hoursAfterMatch: 6,
        isRead: true,
      },
      {
        slug: 'mx-omar-leilani-msg-6',
        senderSlug: 'leilani',
        body: 'Is that your way of volunteering?',
        hoursAfterMatch: 7,
        isRead: true,
      },
      {
        slug: 'mx-omar-leilani-msg-7',
        senderSlug: 'omar',
        body: 'Subtle right? But yeah I would love to run together if you are up for it',
        hoursAfterMatch: 8,
        isRead: true,
      },
    ],
  },

  // ─────────────────────────────────────────────────────────────────
  // TIER 4 — Deepest conversations (13-18 messages)  [5 matches]
  // ─────────────────────────────────────────────────────────────────
  {
    slug: 'mx-taro-alana',
    userSlugs: ['taro', 'alana'],
    dayOffset: 14,
    hour: 10,
    isDatingMatch: true,
    isWorkoutMatch: true,
    isArchived: true,
    messages: [
      {
        slug: 'mx-taro-alana-msg-1',
        senderSlug: 'taro',
        body: 'Hey Alana! I noticed we both listed hiking and swimming. Do you do ocean swims?',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'mx-taro-alana-msg-2',
        senderSlug: 'alana',
        body: 'I do! Usually Lanikai to the Mokulua Islands and back. It is about a mile round trip',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'mx-taro-alana-msg-3',
        senderSlug: 'taro',
        body: 'That is one of my favorite swims! The water clarity there is unreal. Do you go solo?',
        hoursAfterMatch: 3,
        isRead: true,
      },
      {
        slug: 'mx-taro-alana-msg-4',
        senderSlug: 'alana',
        body: 'Usually with a buddy for safety. My regular swim partner just moved to the mainland though so I need a new one',
        hoursAfterMatch: 4,
        isRead: true,
      },
      {
        slug: 'mx-taro-alana-msg-5',
        senderSlug: 'taro',
        body: 'I humbly submit my application. Qualifications: strong swimmer, good conversation, and I always bring snacks for after',
        hoursAfterMatch: 5,
        isRead: true,
      },
      {
        slug: 'mx-taro-alana-msg-6',
        senderSlug: 'alana',
        body: 'Snacks sealed the deal. You are hired. When can you start?',
        hoursAfterMatch: 6,
        isRead: true,
      },
      {
        slug: 'mx-taro-alana-msg-7',
        senderSlug: 'taro',
        body: 'How about Sunday morning? Calm water, early enough to beat the kayak traffic',
        hoursAfterMatch: 7,
        isRead: true,
      },
      {
        slug: 'mx-taro-alana-msg-8',
        senderSlug: 'alana',
        body: 'Perfect. 7am at the beach access by the pillboxes?',
        hoursAfterMatch: 8,
        isRead: true,
      },
      {
        slug: 'mx-taro-alana-msg-9',
        senderSlug: 'taro',
        body: 'Done! BTW I had an amazing time on our hike last weekend. Manoa Falls was beautiful with all the recent rain',
        hoursAfterMatch: 24,
        isRead: true,
      },
      {
        slug: 'mx-taro-alana-msg-10',
        senderSlug: 'alana',
        body: 'Me too! The waterfall was flowing so hard. And that Thai place we found after was incredible',
        hoursAfterMatch: 25,
        isRead: true,
      },
      {
        slug: 'mx-taro-alana-msg-11',
        senderSlug: 'taro',
        body: 'The green curry haunts my dreams. We need to go back. Also I have been thinking about something',
        hoursAfterMatch: 26,
        isRead: true,
      },
      {
        slug: 'mx-taro-alana-msg-12',
        senderSlug: 'alana',
        body: 'Uh oh, thinking is dangerous. What is up?',
        hoursAfterMatch: 27,
        isRead: true,
      },
      {
        slug: 'mx-taro-alana-msg-13',
        senderSlug: 'taro',
        body: 'Good thinking! There is a BRDG group hike to Stairway to Heaven next month. Want to sign up together?',
        hoursAfterMatch: 28,
        isRead: true,
      },
      {
        slug: 'mx-taro-alana-msg-14',
        senderSlug: 'alana',
        body: 'Stairway to Heaven?? I have been wanting to do that forever but it seemed too intense to do alone',
        hoursAfterMatch: 29,
        isRead: true,
      },
      {
        slug: 'mx-taro-alana-msg-15',
        senderSlug: 'taro',
        body: 'That is why we go together. Training plan: ocean swims for cardio, hikes for legs, and lots of green curry for fuel',
        hoursAfterMatch: 30,
        isRead: true,
      },
      {
        slug: 'mx-taro-alana-msg-16',
        senderSlug: 'alana',
        body: 'The perfect training plan does not exi-- oh wait. Sign me up for all of it',
        hoursAfterMatch: 31,
      },
    ],
  },
  {
    slug: 'mx-mika-sasha',
    userSlugs: ['mika', 'sasha'],
    dayOffset: 15,
    hour: 8,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'mx-mika-sasha-msg-1',
        senderSlug: 'mika',
        body: 'Mixed match! I feel like that deserves a special introduction. Hi, I am Mika, and I like long beach runs and short espressos',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'mx-mika-sasha-msg-2',
        senderSlug: 'sasha',
        body: 'Ha! I am Sasha, and I like heavy deadlifts and light conversation. Wait, that came out wrong',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'mx-mika-sasha-msg-3',
        senderSlug: 'mika',
        body: 'No that is perfect actually. So what do you do when you are not deadlifting?',
        hoursAfterMatch: 3,
        isRead: true,
      },
      {
        slug: 'mx-mika-sasha-msg-4',
        senderSlug: 'sasha',
        body: 'I am a marine biologist! Spend a lot of time in the water which doubles as cardio. What about you?',
        hoursAfterMatch: 4,
        isRead: true,
      },
      {
        slug: 'mx-mika-sasha-msg-5',
        senderSlug: 'mika',
        body: 'Software engineer by day, aspiring chef by night. Basically I sit all day then try to undo the damage at the gym',
        hoursAfterMatch: 5,
        isRead: true,
      },
      {
        slug: 'mx-mika-sasha-msg-6',
        senderSlug: 'sasha',
        body: 'A chef! Ok now I really need to hang out with you. I burn water',
        hoursAfterMatch: 6,
        isRead: true,
      },
      {
        slug: 'mx-mika-sasha-msg-7',
        senderSlug: 'mika',
        body: 'Deal - I will cook, you teach me about marine life. Equivalent exchange',
        hoursAfterMatch: 7,
        isRead: true,
      },
      {
        slug: 'mx-mika-sasha-msg-8',
        senderSlug: 'sasha',
        body: 'Ok but first, that workout together we matched for. What is your gym schedule like?',
        hoursAfterMatch: 24,
        isRead: true,
      },
      {
        slug: 'mx-mika-sasha-msg-9',
        senderSlug: 'mika',
        body: 'Usually 6pm after work. Push/pull/legs split. You?',
        hoursAfterMatch: 25,
        isRead: true,
      },
      {
        slug: 'mx-mika-sasha-msg-10',
        senderSlug: 'sasha',
        body: 'Same time! I am at Pacific Fitness on King St. We could do legs together Tuesday?',
        hoursAfterMatch: 26,
        isRead: true,
      },
      {
        slug: 'mx-mika-sasha-msg-11',
        senderSlug: 'mika',
        body: 'Legs day on a first meeting? You are brave. But I am in. Fair warning: I am competitive',
        hoursAfterMatch: 27,
        isRead: true,
      },
      {
        slug: 'mx-mika-sasha-msg-12',
        senderSlug: 'sasha',
        body: 'Good because so am I. And then dinner after? There is an amazing ramen place walking distance from the gym',
        hoursAfterMatch: 28,
        isRead: true,
      },
      {
        slug: 'mx-mika-sasha-msg-13',
        senderSlug: 'mika',
        body: 'Leg day then ramen? You speak my love language. It is a date. Or a workout. Both?',
        hoursAfterMatch: 29,
        isRead: true,
      },
      {
        slug: 'mx-mika-sasha-msg-14',
        senderSlug: 'sasha',
        body: 'Definitely both. The beauty of the mixed match. Oh and update - those sea turtles I have been tracking? One just laid eggs at Laniakea!',
        hoursAfterMatch: 48,
        isRead: true,
      },
      {
        slug: 'mx-mika-sasha-msg-15',
        senderSlug: 'mika',
        body: 'No way!! Can we go see them? I will pack a picnic. Protein-heavy of course since it will be post-leg-day',
        hoursAfterMatch: 49,
      },
      {
        slug: 'mx-mika-sasha-msg-16',
        senderSlug: 'sasha',
        body: 'A protein picnic on turtle beach. I think this is the most us plan possible. Saturday morning?',
        hoursAfterMatch: 50,
      },
    ],
  },
  {
    slug: 'mx-hiroshi-malia',
    userSlugs: ['hiroshi', 'malia'],
    dayOffset: 16,
    hour: 12,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'mx-hiroshi-malia-msg-1',
        senderSlug: 'hiroshi',
        body: 'Your profile is amazing - surfing, yoga, AND marathon running? When do you sleep?',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'mx-hiroshi-malia-msg-2',
        senderSlug: 'malia',
        body: 'Sleep is overrated when you live in Hawaii! But seriously, I am very structured with my training schedule',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'mx-hiroshi-malia-msg-3',
        senderSlug: 'hiroshi',
        body: 'I respect that. I am a physical therapist so I nerd out about training periodization',
        hoursAfterMatch: 3,
        isRead: true,
      },
      {
        slug: 'mx-hiroshi-malia-msg-4',
        senderSlug: 'malia',
        body: 'A PT?? Oh my god I have so many questions about my hip flexor situation',
        hoursAfterMatch: 4,
        isRead: true,
      },
      {
        slug: 'mx-hiroshi-malia-msg-5',
        senderSlug: 'hiroshi',
        body: 'Ha, I get that a lot on dates. But genuinely, tight hip flexors are the number one issue I see in runners',
        hoursAfterMatch: 5,
        isRead: true,
      },
      {
        slug: 'mx-hiroshi-malia-msg-6',
        senderSlug: 'malia',
        body: 'Ok but this is the dream match - someone who actually understands the body. Can we combine a date with a PT assessment?',
        hoursAfterMatch: 6,
        isRead: true,
      },
      {
        slug: 'mx-hiroshi-malia-msg-7',
        senderSlug: 'hiroshi',
        body: 'Most romantic first date ever: foam rolling and movement screening. But actually I know a great way to combine things',
        hoursAfterMatch: 7,
        isRead: true,
      },
      {
        slug: 'mx-hiroshi-malia-msg-8',
        senderSlug: 'malia',
        body: 'I am listening...',
        hoursAfterMatch: 8,
        isRead: true,
      },
      {
        slug: 'mx-hiroshi-malia-msg-9',
        senderSlug: 'hiroshi',
        body: 'Beach yoga session where I incorporate some corrective exercises, then brunch at Bogart\'s Cafe. Best of both worlds',
        hoursAfterMatch: 9,
        isRead: true,
      },
      {
        slug: 'mx-hiroshi-malia-msg-10',
        senderSlug: 'malia',
        body: 'Bogart\'s has the best acai bowls. You know the way to a runner\'s heart. When?',
        hoursAfterMatch: 10,
        isRead: true,
      },
      {
        slug: 'mx-hiroshi-malia-msg-11',
        senderSlug: 'hiroshi',
        body: 'Sunday 7am at Sans Souci Beach? Small, quiet, perfect for yoga',
        hoursAfterMatch: 24,
        isRead: true,
      },
      {
        slug: 'mx-hiroshi-malia-msg-12',
        senderSlug: 'malia',
        body: 'Perfect spot. I will bring my mat and an open mind about my hip flexors',
        hoursAfterMatch: 25,
        isRead: true,
      },
      {
        slug: 'mx-hiroshi-malia-msg-13',
        senderSlug: 'hiroshi',
        body: 'And I will bring the expertise and zero judgment. Also - I signed up for the BRDG beach run next month. Did you see it?',
        hoursAfterMatch: 26,
        isRead: true,
      },
      {
        slug: 'mx-hiroshi-malia-msg-14',
        senderSlug: 'malia',
        body: 'I was literally just looking at that! 10K along Kailua Beach. Want to be running partners?',
        hoursAfterMatch: 27,
        isRead: true,
      },
      {
        slug: 'mx-hiroshi-malia-msg-15',
        senderSlug: 'hiroshi',
        body: 'Nothing I would like more. We can even do a few training runs together before it to find our pace',
        hoursAfterMatch: 28,
        isRead: true,
      },
      {
        slug: 'mx-hiroshi-malia-msg-16',
        senderSlug: 'malia',
        body: 'Yoga dates AND training runs? I think this is the most productive match I have ever had on any app',
        hoursAfterMatch: 48,
      },
      {
        slug: 'mx-hiroshi-malia-msg-17',
        senderSlug: 'hiroshi',
        body: 'Same. Most matches are just small talk. This feels like we are actually building something. See you Sunday!',
        hoursAfterMatch: 49,
      },
    ],
  },
  {
    slug: 'mx-nalu-priya',
    userSlugs: ['nalu', 'priya'],
    dayOffset: 18,
    hour: 6,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'mx-nalu-priya-msg-1',
        senderSlug: 'nalu',
        body: 'A dual match! I take that as the universe giving us both a green light',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'mx-nalu-priya-msg-2',
        senderSlug: 'priya',
        body: 'Ha! I was thinking the same thing. So tell me, what does your ideal active day look like?',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'mx-nalu-priya-msg-3',
        senderSlug: 'nalu',
        body: 'Dawn patrol surf, mid-morning strength session, afternoon hike if I have energy. Then collapse',
        hoursAfterMatch: 3,
        isRead: true,
      },
      {
        slug: 'mx-nalu-priya-msg-4',
        senderSlug: 'priya',
        body: 'That is intense! I love it. Mine is morning yoga, afternoon climbing, evening walk on the beach',
        hoursAfterMatch: 4,
        isRead: true,
      },
      {
        slug: 'mx-nalu-priya-msg-5',
        senderSlug: 'nalu',
        body: 'We could combine these into one epic day. Morning surf and yoga, afternoon climb, evening beach walk. The ultimate first date',
        hoursAfterMatch: 5,
        isRead: true,
      },
      {
        slug: 'mx-nalu-priya-msg-6',
        senderSlug: 'priya',
        body: 'A 12 hour first date?? Bold. I like it but maybe we start with one activity and see if we survive each other',
        hoursAfterMatch: 6,
        isRead: true,
      },
      {
        slug: 'mx-nalu-priya-msg-7',
        senderSlug: 'nalu',
        body: 'Fair point. Ok how about this - sunrise surf lesson from me, brunch at Koko Head Cafe, and we take it from there',
        hoursAfterMatch: 7,
        isRead: true,
      },
      {
        slug: 'mx-nalu-priya-msg-8',
        senderSlug: 'priya',
        body: 'Now that is a plan. I have always wanted to learn to surf but I am honestly a bit scared of the ocean',
        hoursAfterMatch: 8,
        isRead: true,
      },
      {
        slug: 'mx-nalu-priya-msg-9',
        senderSlug: 'nalu',
        body: 'Healthy respect for the ocean is a good thing. I will find us a gentle break - white water only at first. And I will be right there the whole time',
        hoursAfterMatch: 9,
        isRead: true,
      },
      {
        slug: 'mx-nalu-priya-msg-10',
        senderSlug: 'priya',
        body: 'Ok that actually makes me feel a lot better. You seem like a really patient teacher',
        hoursAfterMatch: 24,
        isRead: true,
      },
      {
        slug: 'mx-nalu-priya-msg-11',
        senderSlug: 'nalu',
        body: 'I taught my 70 year old uncle to surf last year so I think I can handle it. Also update - went to the climbing gym you recommended and WOW',
        hoursAfterMatch: 25,
        isRead: true,
      },
      {
        slug: 'mx-nalu-priya-msg-12',
        senderSlug: 'priya',
        body: 'You went already?? What did you think! Did you try the overhang wall?',
        hoursAfterMatch: 26,
        isRead: true,
      },
      {
        slug: 'mx-nalu-priya-msg-13',
        senderSlug: 'nalu',
        body: 'I tried and failed spectacularly. My forearms are still screaming. Surfing muscles and climbing muscles are NOT the same',
        hoursAfterMatch: 27,
        isRead: true,
      },
      {
        slug: 'mx-nalu-priya-msg-14',
        senderSlug: 'priya',
        body: 'Haha welcome to my world! Ok counteroffer - I will teach you climbing technique if you teach me to surf. Fair trade?',
        hoursAfterMatch: 28,
        isRead: true,
      },
      {
        slug: 'mx-nalu-priya-msg-15',
        senderSlug: 'nalu',
        body: 'The fairest trade. Surf Saturdays and Climb Sundays? We could make it a recurring thing',
        hoursAfterMatch: 48,
        isRead: true,
      },
      {
        slug: 'mx-nalu-priya-msg-16',
        senderSlug: 'priya',
        body: 'I love having a regular adventure partner. Also I bought a wetsuit because of you. This is escalating quickly',
        hoursAfterMatch: 49,
      },
      {
        slug: 'mx-nalu-priya-msg-17',
        senderSlug: 'nalu',
        body: 'The wetsuit purchase means there is no going back now. This Saturday, 6am, Waikiki wall. Bring the wetsuit and your courage',
        hoursAfterMatch: 50,
      },
      {
        slug: 'mx-nalu-priya-msg-18',
        senderSlug: 'priya',
        body: 'Courage and SPF 50. See you at dawn, coach',
        hoursAfterMatch: 51,
      },
    ],
  },
];
