import { SeedMatch } from './config';

/**
 * 80 dating-focused seed matches for BRDG.
 *
 * Distribution (78 new + 2 existing):
 *   15 matches with 0 messages
 *   25 matches with 1-2 messages
 *   20 matches with 3-5 messages
 *   12 matches with 6-9 messages
 *    6 matches with 10-15 messages
 *
 * 10 archived, 3 blocked among the 78 new matches.
 * No user appears in more than 8 matches total.
 */
export const datingMatches: SeedMatch[] = [
  // ── Existing matches (preserved exactly) ─────────────────────────
  {
    slug: 'kai-leilani',
    userSlugs: ['kai', 'leilani'],
    dayOffset: 0,
    hour: 9,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      { slug: 'kai-opener', senderSlug: 'kai', body: 'Sunrise run still on if you want a low-pressure first lap.', hoursAfterMatch: 1, isRead: true },
      { slug: 'leilani-reply', senderSlug: 'leilani', body: 'Yes. Coffee after if the pace stays conversational.', hoursAfterMatch: 2 },
    ],
  },
  {
    slug: 'mason-rowan-archived',
    userSlugs: ['mason', 'rowan'],
    dayOffset: 1,
    hour: 18,
    isArchived: true,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      { slug: 'mason-check-in', senderSlug: 'mason', body: 'Good lift. Let me know if you want to repeat it next week.', hoursAfterMatch: 1, isRead: true },
    ],
  },

  // ── 0-message matches (15) ───────────────────────────────────────
  {
    slug: 'noa-priya',
    userSlugs: ['noa', 'priya'],
    dayOffset: 2,
    hour: 10,
    isDatingMatch: true,
    messages: [],
  },
  {
    slug: 'cameron-maren',
    userSlugs: ['cameron', 'maren'],
    dayOffset: 3,
    hour: 14,
    isDatingMatch: true,
    messages: [],
  },
  {
    slug: 'isla-rafael',
    userSlugs: ['isla', 'rafael'],
    dayOffset: 4,
    hour: 8,
    isDatingMatch: true,
    messages: [],
  },
  {
    slug: 'beck-june',
    userSlugs: ['beck', 'june'],
    dayOffset: 5,
    hour: 11,
    isDatingMatch: true,
    messages: [],
  },
  {
    slug: 'luca-arden',
    userSlugs: ['luca', 'arden'],
    dayOffset: 5,
    hour: 16,
    isDatingMatch: true,
    messages: [],
  },
  {
    slug: 'hazel-omar',
    userSlugs: ['hazel', 'omar'],
    dayOffset: 6,
    hour: 9,
    isDatingMatch: true,
    messages: [],
  },
  {
    slug: 'akira-hana',
    userSlugs: ['akira', 'hana'],
    dayOffset: 8,
    hour: 10,
    isDatingMatch: true,
    messages: [],
  },
  {
    slug: 'kenji-mika',
    userSlugs: ['kenji', 'mika'],
    dayOffset: 8,
    hour: 15,
    isDatingMatch: true,
    messages: [],
  },
  {
    slug: 'sora-yuki',
    userSlugs: ['sora', 'yuki'],
    dayOffset: 9,
    hour: 7,
    isDatingMatch: true,
    messages: [],
  },
  {
    slug: 'taro-riko',
    userSlugs: ['taro', 'riko'],
    dayOffset: 9,
    hour: 13,
    isDatingMatch: true,
    messages: [],
  },
  {
    slug: 'aiko-hiroshi',
    userSlugs: ['aiko', 'hiroshi'],
    dayOffset: 10,
    hour: 8,
    isDatingMatch: true,
    messages: [],
  },

  // ── 1-2 message matches (25) ─────────────────────────────────────
  {
    slug: 'jordan-tessa',
    userSlugs: ['jordan', 'tessa'],
    dayOffset: 2,
    hour: 11,
    isDatingMatch: true,
    messages: [
      { slug: 'jordan-tessa-msg-1', senderSlug: 'jordan', body: 'Your trail running photos are incredible. Do you hit Koko Head often?', hoursAfterMatch: 1 },
    ],
  },
  {
    slug: 'nia-keoni',
    userSlugs: ['nia', 'keoni'],
    dayOffset: 2,
    hour: 15,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      { slug: 'nia-keoni-msg-1', senderSlug: 'nia', body: 'I saw you do outrigger paddling. I have always wanted to try that!', hoursAfterMatch: 2, isRead: true },
      { slug: 'nia-keoni-msg-2', senderSlug: 'keoni', body: 'Happy to take you out sometime. Calm water mornings are the best for beginners.', hoursAfterMatch: 4 },
    ],
  },
  {
    slug: 'sasha-eli',
    userSlugs: ['sasha', 'eli'],
    dayOffset: 3,
    hour: 9,
    isDatingMatch: true,
    messages: [
      { slug: 'sasha-eli-msg-1', senderSlug: 'sasha', body: 'Fellow early-morning gym person! What time do you usually go?', hoursAfterMatch: 1, isRead: true },
      { slug: 'sasha-eli-msg-2', senderSlug: 'eli', body: '5:30 most days. The gym is basically empty and the vibes are great.', hoursAfterMatch: 3 },
    ],
  },
  {
    slug: 'alana-devon',
    userSlugs: ['alana', 'devon'],
    dayOffset: 3,
    hour: 20,
    isDatingMatch: true,
    messages: [
      { slug: 'alana-devon-msg-1', senderSlug: 'alana', body: 'Your bio cracked me up. Are you really training for a half-marathon in slippers?', hoursAfterMatch: 1 },
    ],
  },
  {
    slug: 'cole-malia',
    userSlugs: ['cole', 'malia'],
    dayOffset: 4,
    hour: 13,
    isDatingMatch: true,
    messages: [
      { slug: 'cole-malia-msg-1', senderSlug: 'cole', body: 'I noticed we both listed hiking as a top activity. Lanikai Pillbox this weekend?', hoursAfterMatch: 2, isRead: true },
      { slug: 'cole-malia-msg-2', senderSlug: 'malia', body: 'That is literally my favorite hike. Sunrise or sunset?', hoursAfterMatch: 5 },
    ],
  },
  {
    slug: 'lani-makoa',
    userSlugs: ['lani', 'makoa'],
    dayOffset: 5,
    hour: 8,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      { slug: 'lani-makoa-msg-1', senderSlug: 'makoa', body: 'Your yoga-on-the-beach photos are so peaceful. Do you teach classes?', hoursAfterMatch: 3, isRead: true },
      { slug: 'lani-makoa-msg-2', senderSlug: 'lani', body: 'Not officially, but I lead a small group Saturday mornings at Ala Moana. You should come!', hoursAfterMatch: 6 },
    ],
  },
  {
    slug: 'hoku-mahina',
    userSlugs: ['hoku', 'mahina'],
    dayOffset: 6,
    hour: 14,
    isDatingMatch: true,
    messages: [
      { slug: 'hoku-mahina-msg-1', senderSlug: 'hoku', body: 'Do you ever climb at the Volcanic Rock Gym? I just started bouldering.', hoursAfterMatch: 2, isRead: true },
      { slug: 'hoku-mahina-msg-2', senderSlug: 'mahina', body: 'All the time! I go Tuesdays and Thursdays. Come join, I can show you the V2 routes.', hoursAfterMatch: 4 },
    ],
  },
  {
    slug: 'kalani-keala',
    userSlugs: ['kalani', 'keala'],
    dayOffset: 7,
    hour: 18,
    isDatingMatch: true,
    messages: [
      { slug: 'kalani-keala-msg-1', senderSlug: 'kalani', body: 'You had me at "trail runner who also surfs." That combination is rare.', hoursAfterMatch: 2, isRead: true },
      { slug: 'kalani-keala-msg-2', senderSlug: 'keala', body: 'Ha, two things that keep me sane. Which trails do you usually run?', hoursAfterMatch: 5 },
    ],
  },
  {
    slug: 'tia-rafa',
    userSlugs: ['tia', 'rafa'],
    dayOffset: 8,
    hour: 20,
    isDatingMatch: true,
    messages: [
      { slug: 'tia-rafa-msg-1', senderSlug: 'tia', body: 'Your CrossFit videos are impressive. How long have you been at it?', hoursAfterMatch: 1, isRead: true },
      { slug: 'tia-rafa-msg-2', senderSlug: 'rafa', body: 'About three years now. It is addictive once you get past the first month.', hoursAfterMatch: 3 },
    ],
  },
  {
    slug: 'nina-marco',
    userSlugs: ['nina', 'marco'],
    dayOffset: 9,
    hour: 12,
    isDatingMatch: true,
    messages: [
      { slug: 'nina-marco-msg-1', senderSlug: 'nina', body: 'I like that you are into cycling. Any good routes around the island?', hoursAfterMatch: 2 },
    ],
  },
  {
    slug: 'dani-sol',
    userSlugs: ['dani', 'sol'],
    dayOffset: 9,
    hour: 16,
    isDatingMatch: true,
    messages: [
      { slug: 'dani-sol-msg-1', senderSlug: 'sol', body: 'Your smile in that hiking photo is contagious. Where was that taken?', hoursAfterMatch: 1, isRead: true },
      { slug: 'dani-sol-msg-2', senderSlug: 'dani', body: 'Stairway to Heaven! Totally worth the early wake-up.', hoursAfterMatch: 4 },
    ],
  },
  {
    slug: 'zara-jax',
    userSlugs: ['zara', 'jax'],
    dayOffset: 10,
    hour: 10,
    isDatingMatch: true,
    messages: [
      { slug: 'zara-jax-msg-1', senderSlug: 'zara', body: 'Fellow boxing fan! Do you spar or mostly bag work?', hoursAfterMatch: 2 },
    ],
  },
  {
    slug: 'sky-rio',
    userSlugs: ['sky', 'rio'],
    dayOffset: 10,
    hour: 15,
    isDatingMatch: true,
    messages: [
      { slug: 'sky-rio-msg-1', senderSlug: 'rio', body: 'Your bio said you are new to the island. Welcome! What has been your favorite spot so far?', hoursAfterMatch: 1, isRead: true },
      { slug: 'sky-rio-msg-2', senderSlug: 'sky', body: 'Definitely North Shore. The waves are wild even just to watch.', hoursAfterMatch: 3 },
    ],
  },
  {
    slug: 'wren-sage',
    userSlugs: ['wren', 'sage'],
    dayOffset: 11,
    hour: 14,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      { slug: 'wren-sage-msg-1', senderSlug: 'wren', body: 'Another morning runner! What pace do you usually keep?', hoursAfterMatch: 1, isRead: true },
      { slug: 'wren-sage-msg-2', senderSlug: 'sage', body: 'About an 8:30 mile for easy runs. Faster if someone is keeping me honest.', hoursAfterMatch: 4 },
    ],
  },
  {
    slug: 'reed-blake',
    userSlugs: ['reed', 'blake'],
    dayOffset: 12,
    hour: 7,
    isDatingMatch: true,
    messages: [
      { slug: 'reed-blake-msg-1', senderSlug: 'reed', body: 'Your climbing photos are wild. Indoor or outdoor preference?', hoursAfterMatch: 3 },
    ],
  },
  {
    slug: 'quinn-kit',
    userSlugs: ['quinn', 'kit'],
    dayOffset: 12,
    hour: 19,
    isDatingMatch: true,
    messages: [
      { slug: 'quinn-kit-msg-1', senderSlug: 'kit', body: 'Saw you are into Pilates. I have been thinking about adding it for flexibility work.', hoursAfterMatch: 1 },
    ],
  },
  {
    slug: 'nova-kira',
    userSlugs: ['nova', 'kira'],
    dayOffset: 13,
    hour: 10,
    isDatingMatch: true,
    messages: [
      { slug: 'nova-kira-msg-1', senderSlug: 'nova', body: 'Your dance background is cool. Does it help with your other training?', hoursAfterMatch: 2, isRead: true },
      { slug: 'nova-kira-msg-2', senderSlug: 'kira', body: 'Hugely! Balance and coordination transfer to almost everything.', hoursAfterMatch: 5 },
    ],
  },
  {
    slug: 'beau-jude',
    userSlugs: ['beau', 'jude'],
    dayOffset: 14,
    hour: 12,
    isDatingMatch: true,
    messages: [
      { slug: 'beau-jude-msg-1', senderSlug: 'beau', body: 'Your strength numbers are legit. How long have you been lifting?', hoursAfterMatch: 2, isRead: true },
      { slug: 'beau-jude-msg-2', senderSlug: 'jude', body: 'About five years seriously. Started in college and never looked back.', hoursAfterMatch: 6 },
    ],
  },

  // ── 3-5 message matches (20) ─────────────────────────────────────
  {
    slug: 'pearl-fern',
    userSlugs: ['pearl', 'fern'],
    dayOffset: 2,
    hour: 12,
    isDatingMatch: true,
    messages: [
      { slug: 'pearl-fern-msg-1', senderSlug: 'pearl', body: 'Your bio about finding zen through burpees really got me.', hoursAfterMatch: 1, isRead: true },
      { slug: 'pearl-fern-msg-2', senderSlug: 'fern', body: 'Ha! It is honestly the only way I can meditate. Moving meditation.', hoursAfterMatch: 3, isRead: true },
      { slug: 'pearl-fern-msg-3', senderSlug: 'pearl', body: 'Have you tried yoga? Might scratch the same itch with less impact.', hoursAfterMatch: 5 },
    ],
  },
  {
    slug: 'dale-clay',
    userSlugs: ['dale', 'clay'],
    dayOffset: 3,
    hour: 11,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      { slug: 'dale-clay-msg-1', senderSlug: 'dale', body: 'I see you are a surfer too. What is your go-to break?', hoursAfterMatch: 1, isRead: true },
      { slug: 'dale-clay-msg-2', senderSlug: 'clay', body: 'Queens on mellow days, Bowls when I want a challenge. You?', hoursAfterMatch: 2, isRead: true },
      { slug: 'dale-clay-msg-3', senderSlug: 'dale', body: 'Canoes mostly. Still working on my cutback.', hoursAfterMatch: 4, isRead: true },
      { slug: 'dale-clay-msg-4', senderSlug: 'clay', body: 'We should paddle out together sometime. I can give you some tips.', hoursAfterMatch: 6 },
    ],
  },
  {
    slug: 'cora-vera',
    userSlugs: ['cora', 'vera'],
    dayOffset: 4,
    hour: 10,
    isDatingMatch: true,
    messages: [
      { slug: 'cora-vera-msg-1', senderSlug: 'cora', body: 'Your hiking photos are gorgeous. Is that Aiea Loop?', hoursAfterMatch: 1, isRead: true },
      { slug: 'cora-vera-msg-2', senderSlug: 'vera', body: 'Good eye! That one is my weekly reset hike.', hoursAfterMatch: 2, isRead: true },
      { slug: 'cora-vera-msg-3', senderSlug: 'cora', body: 'I usually do Manoa Falls but looking for something longer. Would you want to go together?', hoursAfterMatch: 5 },
    ],
  },
  {
    slug: 'lark-opal',
    userSlugs: ['lark', 'opal'],
    dayOffset: 5,
    hour: 13,
    isDatingMatch: true,
    messages: [
      { slug: 'lark-opal-msg-1', senderSlug: 'lark', body: 'Another swimmer! Pool or open water?', hoursAfterMatch: 1, isRead: true },
      { slug: 'lark-opal-msg-2', senderSlug: 'opal', body: 'Open water all the way. Nothing beats Ala Moana in the morning.', hoursAfterMatch: 3, isRead: true },
      { slug: 'lark-opal-msg-3', senderSlug: 'lark', body: 'That sounds perfect. I have been wanting a swim buddy for the longer distances.', hoursAfterMatch: 5, isRead: true },
      { slug: 'lark-opal-msg-4', senderSlug: 'opal', body: 'I am so down. Saturday morning? We can grab acai after.', hoursAfterMatch: 8 },
      { slug: 'lark-opal-msg-5', senderSlug: 'lark', body: 'Yes! That is literally my ideal morning. See you at 7?', hoursAfterMatch: 10 },
    ],
  },
  {
    slug: 'ruth-nell',
    userSlugs: ['ruth', 'nell'],
    dayOffset: 5,
    hour: 19,
    isDatingMatch: true,
    messages: [
      { slug: 'ruth-nell-msg-1', senderSlug: 'ruth', body: 'I love that your profile mentions mobility work. Nobody talks about that enough.', hoursAfterMatch: 1, isRead: true },
      { slug: 'ruth-nell-msg-2', senderSlug: 'nell', body: 'Right? Foam rolling changed my life. Are you into recovery stuff too?', hoursAfterMatch: 2, isRead: true },
      { slug: 'ruth-nell-msg-3', senderSlug: 'ruth', body: 'Huge fan of contrast showers and stretching. We should swap routines sometime.', hoursAfterMatch: 4 },
    ],
  },
  {
    slug: 'bree-shay',
    userSlugs: ['bree', 'shay'],
    dayOffset: 6,
    hour: 11,
    isDatingMatch: true,
    messages: [
      { slug: 'bree-shay-msg-1', senderSlug: 'bree', body: 'Your cycling routes look scenic. Do you ever ride the North Shore loop?', hoursAfterMatch: 1, isRead: true },
      { slug: 'bree-shay-msg-2', senderSlug: 'shay', body: 'Every other weekend! It is the best ride on the island in my opinion.', hoursAfterMatch: 3, isRead: true },
      { slug: 'bree-shay-msg-3', senderSlug: 'bree', body: 'I have only done it once. Would you mind if I tagged along next time?', hoursAfterMatch: 5, isRead: true },
      { slug: 'bree-shay-msg-4', senderSlug: 'shay', body: 'Would love the company. We can stop at the shrimp trucks after.', hoursAfterMatch: 7 },
    ],
  },
  {
    slug: 'emi-yuna',
    userSlugs: ['emi', 'yuna'],
    dayOffset: 7,
    hour: 10,
    isDatingMatch: true,
    messages: [
      { slug: 'emi-yuna-msg-1', senderSlug: 'emi', body: 'We matched on a rest day for me. What does your rest day look like?', hoursAfterMatch: 1, isRead: true },
      { slug: 'emi-yuna-msg-2', senderSlug: 'yuna', body: 'Gentle yoga and maybe a beach walk. Nothing too intense.', hoursAfterMatch: 2, isRead: true },
      { slug: 'emi-yuna-msg-3', senderSlug: 'emi', body: 'That sounds perfect. Want to do a beach walk together sometime?', hoursAfterMatch: 4 },
    ],
  },
  {
    slug: 'kenzo-ren',
    userSlugs: ['kenzo', 'ren'],
    dayOffset: 8,
    hour: 14,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      { slug: 'kenzo-ren-msg-1', senderSlug: 'kenzo', body: 'Your martial arts background is impressive. What discipline?', hoursAfterMatch: 1, isRead: true },
      { slug: 'kenzo-ren-msg-2', senderSlug: 'ren', body: 'Judo primarily, but I have been getting into BJJ recently.', hoursAfterMatch: 3, isRead: true },
      { slug: 'kenzo-ren-msg-3', senderSlug: 'kenzo', body: 'I do karate. We should train together sometime. Always fun to cross-train.', hoursAfterMatch: 5, isRead: true },
      { slug: 'kenzo-ren-msg-4', senderSlug: 'ren', body: 'For sure. There is a great open mat at my gym on Sundays.', hoursAfterMatch: 8 },
      { slug: 'kenzo-ren-msg-5', senderSlug: 'kenzo', body: 'This Sunday works for me. And maybe lunch after?', hoursAfterMatch: 10 },
    ],
  },
  {
    slug: 'ami-toby',
    userSlugs: ['ami', 'toby'],
    dayOffset: 9,
    hour: 8,
    isDatingMatch: true,
    messages: [
      { slug: 'ami-toby-msg-1', senderSlug: 'ami', body: 'Your running pace is impressive. Are you training for anything specific?', hoursAfterMatch: 1, isRead: true },
      { slug: 'ami-toby-msg-2', senderSlug: 'toby', body: 'Honolulu Marathon in December! It will be my first.', hoursAfterMatch: 2, isRead: true },
      { slug: 'ami-toby-msg-3', senderSlug: 'ami', body: 'That is exciting! I did it last year. Happy to share my training plan if you want.', hoursAfterMatch: 4 },
    ],
  },
  {
    slug: 'drew-lia',
    userSlugs: ['drew', 'lia'],
    dayOffset: 10,
    hour: 11,
    isDatingMatch: true,
    messages: [
      { slug: 'drew-lia-msg-1', senderSlug: 'drew', body: 'Your sunset yoga photo is stunning. Where was that?', hoursAfterMatch: 1, isRead: true },
      { slug: 'drew-lia-msg-2', senderSlug: 'lia', body: 'Magic Island! Best spot for sunset practice on Oahu.', hoursAfterMatch: 3, isRead: true },
      { slug: 'drew-lia-msg-3', senderSlug: 'drew', body: 'I am more of a gym person but you are making me want to try outdoor yoga.', hoursAfterMatch: 5, isRead: true },
      { slug: 'drew-lia-msg-4', senderSlug: 'lia', body: 'Bring a mat Wednesday evening. I will show you the spot. No experience needed.', hoursAfterMatch: 8 },
    ],
  },
  {
    slug: 'ada-ivy',
    userSlugs: ['ada', 'ivy'],
    dayOffset: 11,
    hour: 16,
    isDatingMatch: true,
    messages: [
      { slug: 'ada-ivy-msg-1', senderSlug: 'ada', body: 'I see you are into strength training and hiking. That combo builds serious legs.', hoursAfterMatch: 1, isRead: true },
      { slug: 'ada-ivy-msg-2', senderSlug: 'ivy', body: 'Ha, guilty. My quads thank me on the trails though.', hoursAfterMatch: 2, isRead: true },
      { slug: 'ada-ivy-msg-3', senderSlug: 'ada', body: 'Same. Have you done Olomana? That third peak is no joke.', hoursAfterMatch: 5 },
    ],
  },
  {
    slug: 'nora-cameron',
    userSlugs: ['nora', 'cameron'],
    dayOffset: 12,
    hour: 9,
    isDatingMatch: true,
    messages: [
      { slug: 'nora-cameron-msg-1', senderSlug: 'nora', body: 'Your volleyball photos look like so much fun. Is that Queen\'s Beach?', hoursAfterMatch: 1, isRead: true },
      { slug: 'nora-cameron-msg-2', senderSlug: 'cameron', body: 'Yes! We play pickup there every Saturday. You should come by.', hoursAfterMatch: 3, isRead: true },
      { slug: 'nora-cameron-msg-3', senderSlug: 'nora', body: 'I am not great but I love playing. What time do you usually start?', hoursAfterMatch: 5, isRead: true },
      { slug: 'nora-cameron-msg-4', senderSlug: 'cameron', body: 'Around 10am. Skill level is all over the place so no pressure at all.', hoursAfterMatch: 7 },
    ],
  },
  {
    slug: 'priya-luca',
    userSlugs: ['priya', 'luca'],
    dayOffset: 12,
    hour: 18,
    isDatingMatch: true,
    messages: [
      { slug: 'priya-luca-msg-1', senderSlug: 'priya', body: 'What got you into boxing? I have been thinking about starting.', hoursAfterMatch: 1, isRead: true },
      { slug: 'priya-luca-msg-2', senderSlug: 'luca', body: 'Stress relief honestly. Hitting pads is the best therapy.', hoursAfterMatch: 2, isRead: true },
      { slug: 'priya-luca-msg-3', senderSlug: 'priya', body: 'I believe it. Any gym recommendations for beginners?', hoursAfterMatch: 4 },
    ],
  },
  {
    slug: 'maren-rafael',
    userSlugs: ['maren', 'rafael'],
    dayOffset: 13,
    hour: 13,
    isDatingMatch: true,
    messages: [
      { slug: 'maren-rafael-msg-1', senderSlug: 'maren', body: 'You mentioned you cook for meal prep. What is your go-to post-workout meal?', hoursAfterMatch: 1, isRead: true },
      { slug: 'maren-rafael-msg-2', senderSlug: 'rafael', body: 'Salmon bowl with rice and avocado. Simple but hits every macro.', hoursAfterMatch: 3, isRead: true },
      { slug: 'maren-rafael-msg-3', senderSlug: 'maren', body: 'A person after my own heart. I do something similar but with chicken.', hoursAfterMatch: 5, isRead: true },
      { slug: 'maren-rafael-msg-4', senderSlug: 'rafael', body: 'We should have a cook-off sometime. Loser buys smoothies after.', hoursAfterMatch: 8 },
      { slug: 'maren-rafael-msg-5', senderSlug: 'maren', body: 'You are on. Name the date.', hoursAfterMatch: 10 },
    ],
  },
  {
    slug: 'eli-june',
    userSlugs: ['eli', 'june'],
    dayOffset: 14,
    hour: 10,
    isDatingMatch: true,
    messages: [
      { slug: 'eli-june-msg-1', senderSlug: 'eli', body: 'Your profile says you are into dance fitness. What kind?', hoursAfterMatch: 1, isRead: true },
      { slug: 'eli-june-msg-2', senderSlug: 'june', body: 'Mostly Zumba and hip-hop cardio. It does not feel like working out.', hoursAfterMatch: 3, isRead: true },
      { slug: 'eli-june-msg-3', senderSlug: 'eli', body: 'I have zero coordination but I am weirdly curious now.', hoursAfterMatch: 5 },
    ],
  },
  {
    slug: 'keoni-isla',
    userSlugs: ['keoni', 'isla'],
    dayOffset: 14,
    hour: 16,
    isDatingMatch: true,
    messages: [
      { slug: 'keoni-isla-msg-1', senderSlug: 'keoni', body: 'Love that you are into both surfing and yoga. The balance must help.', hoursAfterMatch: 1, isRead: true },
      { slug: 'keoni-isla-msg-2', senderSlug: 'isla', body: 'Totally. Yoga fixed my pop-up entirely. Plus it is great for recovery.', hoursAfterMatch: 2, isRead: true },
      { slug: 'keoni-isla-msg-3', senderSlug: 'keoni', body: 'I should try that. My pop-up could use some work honestly.', hoursAfterMatch: 4, isRead: true },
      { slug: 'keoni-isla-msg-4', senderSlug: 'isla', body: 'Come to my class! Surf-specific yoga, every Sunday at 8am.', hoursAfterMatch: 7 },
    ],
  },
  {
    slug: 'devon-hazel',
    userSlugs: ['devon', 'hazel'],
    dayOffset: 15,
    hour: 11,
    isDatingMatch: true,
    messages: [
      { slug: 'devon-hazel-msg-1', senderSlug: 'devon', body: 'I see you also run the Diamond Head trail. That sunrise view never gets old.', hoursAfterMatch: 1, isRead: true },
      { slug: 'devon-hazel-msg-2', senderSlug: 'hazel', body: 'Agreed. I try to go at least twice a month. Great cardio too.', hoursAfterMatch: 2, isRead: true },
      { slug: 'devon-hazel-msg-3', senderSlug: 'devon', body: 'Want to race up it sometime? Loser buys shave ice at Matsumoto\'s.', hoursAfterMatch: 5 },
    ],
  },
  {
    slug: 'tessa-noa',
    userSlugs: ['tessa', 'noa'],
    dayOffset: 15,
    hour: 20,
    isDatingMatch: true,
    messages: [
      { slug: 'tessa-noa-msg-1', senderSlug: 'tessa', body: 'Your swimming times are impressive. Do you compete?', hoursAfterMatch: 1, isRead: true },
      { slug: 'tessa-noa-msg-2', senderSlug: 'noa', body: 'Masters meets a couple times a year. Mostly for fun at this point.', hoursAfterMatch: 3, isRead: true },
      { slug: 'tessa-noa-msg-3', senderSlug: 'tessa', body: 'I have been wanting to join a masters program. Any advice on getting started?', hoursAfterMatch: 5, isRead: true },
      { slug: 'tessa-noa-msg-4', senderSlug: 'noa', body: 'Just show up! My team practices at the Palolo pool. Wednesday at 6pm if you want to try.', hoursAfterMatch: 8 },
    ],
  },
  {
    slug: 'sasha-beck',
    userSlugs: ['sasha', 'beck'],
    dayOffset: 16,
    hour: 9,
    isDatingMatch: true,
    messages: [
      { slug: 'sasha-beck-msg-1', senderSlug: 'sasha', body: 'I noticed we both go to the same gym. How have we not crossed paths?', hoursAfterMatch: 1, isRead: true },
      { slug: 'sasha-beck-msg-2', senderSlug: 'beck', body: 'I am usually there super early. Like 5am early.', hoursAfterMatch: 3, isRead: true },
      { slug: 'sasha-beck-msg-3', senderSlug: 'sasha', body: 'That explains it. I am more of a 7am person. Maybe I should come earlier.', hoursAfterMatch: 5 },
    ],
  },

  // ── 6-9 message matches (12) ─────────────────────────────────────
  {
    slug: 'jordan-malia',
    userSlugs: ['jordan', 'malia'],
    dayOffset: 3,
    hour: 16,
    isDatingMatch: true,
    messages: [
      { slug: 'jordan-malia-msg-1', senderSlug: 'jordan', body: 'Your profile is refreshing. Most people do not mention their actual workout split.', hoursAfterMatch: 1, isRead: true },
      { slug: 'jordan-malia-msg-2', senderSlug: 'malia', body: 'I figure honesty up front saves time. PPL split, six days a week.', hoursAfterMatch: 2, isRead: true },
      { slug: 'jordan-malia-msg-3', senderSlug: 'jordan', body: 'Same here. What gym do you go to?', hoursAfterMatch: 4, isRead: true },
      { slug: 'jordan-malia-msg-4', senderSlug: 'malia', body: 'Iron Paradise in Kailua. Small but has everything I need.', hoursAfterMatch: 6, isRead: true },
      { slug: 'jordan-malia-msg-5', senderSlug: 'jordan', body: 'No way. I have been thinking about switching there. How are the squat racks?', hoursAfterMatch: 8, isRead: true },
      { slug: 'jordan-malia-msg-6', senderSlug: 'malia', body: 'Three racks and they are almost never all taken. Come check it out.', hoursAfterMatch: 10 },
      { slug: 'jordan-malia-msg-7', senderSlug: 'jordan', body: 'Would tomorrow work? I could use a spotter for heavy squats anyway.', hoursAfterMatch: 12 },
    ],
  },
  {
    slug: 'nia-cole',
    userSlugs: ['nia', 'cole'],
    dayOffset: 4,
    hour: 15,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      { slug: 'nia-cole-msg-1', senderSlug: 'nia', body: 'I see we are both into trail running. What is the longest trail you have done on Oahu?', hoursAfterMatch: 1, isRead: true },
      { slug: 'nia-cole-msg-2', senderSlug: 'cole', body: 'The full Kuli\'ou\'ou Ridge. About 5 miles round trip. Steep but worth it.', hoursAfterMatch: 2, isRead: true },
      { slug: 'nia-cole-msg-3', senderSlug: 'nia', body: 'Impressive! I maxed out at Makapu\'u Lighthouse so far. Baby steps.', hoursAfterMatch: 4, isRead: true },
      { slug: 'nia-cole-msg-4', senderSlug: 'cole', body: 'That is a great one though. The whale watching from up there is incredible.', hoursAfterMatch: 6, isRead: true },
      { slug: 'nia-cole-msg-5', senderSlug: 'nia', body: 'Yes! I went during whale season and it was magical.', hoursAfterMatch: 8, isRead: true },
      { slug: 'nia-cole-msg-6', senderSlug: 'cole', body: 'Want to do a trail together this weekend? I know a great moderate one.', hoursAfterMatch: 10, isRead: true },
      { slug: 'nia-cole-msg-7', senderSlug: 'nia', body: 'I would love that. Saturday morning works for me.', hoursAfterMatch: 12 },
      { slug: 'nia-cole-msg-8', senderSlug: 'cole', body: 'Saturday it is. I will send you the trailhead pin. Bring water and sunscreen.', hoursAfterMatch: 14 },
    ],
  },
  {
    slug: 'alana-remy',
    userSlugs: ['alana', 'remy'],
    dayOffset: 6,
    hour: 8,
    isDatingMatch: true,
    messages: [
      { slug: 'alana-remy-msg-1', senderSlug: 'alana', body: 'Your surfing photos are making me jealous. I have been trying to learn.', hoursAfterMatch: 1, isRead: true },
      { slug: 'alana-remy-msg-2', senderSlug: 'remy', body: 'It takes time but it is so worth it. Where have you been practicing?', hoursAfterMatch: 2, isRead: true },
      { slug: 'alana-remy-msg-3', senderSlug: 'alana', body: 'Waikiki mostly. The waves are small enough that I do not embarrass myself too much.', hoursAfterMatch: 4, isRead: true },
      { slug: 'alana-remy-msg-4', senderSlug: 'remy', body: 'That is the perfect spot to learn! Are you on a foamie or a hard board?', hoursAfterMatch: 6, isRead: true },
      { slug: 'alana-remy-msg-5', senderSlug: 'alana', body: 'Still on the foamie. My pop-up needs serious work.', hoursAfterMatch: 8, isRead: true },
      { slug: 'alana-remy-msg-6', senderSlug: 'remy', body: 'Let me help! I do surf coaching on the side. First lesson is on me.', hoursAfterMatch: 10 },
    ],
  },
  {
    slug: 'rowan-celine',
    userSlugs: ['rowan', 'celine'],
    dayOffset: 7,
    hour: 15,
    isDatingMatch: true,
    messages: [
      { slug: 'rowan-celine-msg-1', senderSlug: 'rowan', body: 'Your kickboxing highlights are intense. How long have you been training?', hoursAfterMatch: 1, isRead: true },
      { slug: 'rowan-celine-msg-2', senderSlug: 'celine', body: 'Almost four years now. It started as cardio and became a lifestyle.', hoursAfterMatch: 2, isRead: true },
      { slug: 'rowan-celine-msg-3', senderSlug: 'rowan', body: 'I can relate. Weightlifting did the same for me. Started for aesthetics, stayed for the mental health.', hoursAfterMatch: 4, isRead: true },
      { slug: 'rowan-celine-msg-4', senderSlug: 'celine', body: 'That is exactly it. Do you think our training styles would clash or complement?', hoursAfterMatch: 6, isRead: true },
      { slug: 'rowan-celine-msg-5', senderSlug: 'rowan', body: 'Complement for sure. Strength helps everything. Want to try a combined session?', hoursAfterMatch: 8, isRead: true },
      { slug: 'rowan-celine-msg-6', senderSlug: 'celine', body: 'I am in. Kickboxing then weights? Or the other way around?', hoursAfterMatch: 10, isRead: true },
      { slug: 'rowan-celine-msg-7', senderSlug: 'rowan', body: 'Kickboxing first while we are fresh. Then I will show you my favorite upper body circuit.', hoursAfterMatch: 12 },
    ],
  },
  {
    slug: 'mason-nora',
    userSlugs: ['mason', 'nora'],
    dayOffset: 9,
    hour: 10,
    isDatingMatch: true,
    messages: [
      { slug: 'mason-nora-msg-1', senderSlug: 'mason', body: 'Hey Nora. Your bio about hiking every weekend really stood out.', hoursAfterMatch: 1, isRead: true },
      { slug: 'mason-nora-msg-2', senderSlug: 'nora', body: 'Thanks! It is my way of exploring the island. I moved here a year ago.', hoursAfterMatch: 3, isRead: true },
      { slug: 'mason-nora-msg-3', senderSlug: 'mason', body: 'Same actually. Have you done the Waimano Falls trail yet?', hoursAfterMatch: 5, isRead: true },
      { slug: 'mason-nora-msg-4', senderSlug: 'nora', body: 'Not yet! It has been on my list. Is it worth the drive?', hoursAfterMatch: 7, isRead: true },
      { slug: 'mason-nora-msg-5', senderSlug: 'mason', body: 'Absolutely. The swimming hole at the end is the best reward.', hoursAfterMatch: 9, isRead: true },
      { slug: 'mason-nora-msg-6', senderSlug: 'nora', body: 'That sounds amazing. Would you want to go together? I hate hiking alone in new spots.', hoursAfterMatch: 11 },
      { slug: 'mason-nora-msg-7', senderSlug: 'mason', body: 'I was hoping you would say that. How about next Saturday?', hoursAfterMatch: 13 },
      { slug: 'mason-nora-msg-8', senderSlug: 'nora', body: 'Perfect. I will pack extra snacks. Fair warning, I take a lot of photos.', hoursAfterMatch: 16 },
    ],
  },
  {
    slug: 'mika-taro',
    userSlugs: ['mika', 'taro'],
    dayOffset: 11,
    hour: 12,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      { slug: 'mika-taro-msg-1', senderSlug: 'mika', body: 'Your calisthenics videos are really impressive. Self-taught?', hoursAfterMatch: 1, isRead: true },
      { slug: 'mika-taro-msg-2', senderSlug: 'taro', body: 'Mostly YouTube and a lot of trial and error. Took me two years to get a muscle-up.', hoursAfterMatch: 3, isRead: true },
      { slug: 'mika-taro-msg-3', senderSlug: 'mika', body: 'Two years of dedication though. That is what I admire. I am trying to learn handstands.', hoursAfterMatch: 5, isRead: true },
      { slug: 'mika-taro-msg-4', senderSlug: 'taro', body: 'Wall walks are the key. Do them every day and you will progress fast.', hoursAfterMatch: 7, isRead: true },
      { slug: 'mika-taro-msg-5', senderSlug: 'mika', body: 'Good tip! Do you ever train at the outdoor bars at Kapiolani Park?', hoursAfterMatch: 9, isRead: true },
      { slug: 'mika-taro-msg-6', senderSlug: 'taro', body: 'That is my main spot. Sunday mornings there is a whole crew.', hoursAfterMatch: 11 },
      { slug: 'mika-taro-msg-7', senderSlug: 'mika', body: 'Mind if I come by this Sunday? Promise I will not slow you down too much.', hoursAfterMatch: 14 },
    ],
  },
  {
    slug: 'leilani-finn',
    userSlugs: ['leilani', 'finn'],
    dayOffset: 12,
    hour: 14,
    isDatingMatch: true,
    messages: [
      { slug: 'leilani-finn-msg-1', senderSlug: 'leilani', body: 'Hey Finn! I saw your bio mentions you are a freediver. How deep have you gone?', hoursAfterMatch: 1, isRead: true },
      { slug: 'leilani-finn-msg-2', senderSlug: 'finn', body: 'My personal best is 25 meters. Still working toward 30. Do you dive?', hoursAfterMatch: 2, isRead: true },
      { slug: 'leilani-finn-msg-3', senderSlug: 'leilani', body: 'Snorkeling only for now but freediving has always fascinated me.', hoursAfterMatch: 4, isRead: true },
      { slug: 'leilani-finn-msg-4', senderSlug: 'finn', body: 'The breath work is the best part. It is basically meditation underwater.', hoursAfterMatch: 6, isRead: true },
      { slug: 'leilani-finn-msg-5', senderSlug: 'leilani', body: 'That sounds incredible. I would love to learn the basics sometime.', hoursAfterMatch: 8, isRead: true },
      { slug: 'leilani-finn-msg-6', senderSlug: 'finn', body: 'We could start with pool breath-hold training. It is safe and actually really fun.', hoursAfterMatch: 10 },
      { slug: 'leilani-finn-msg-7', senderSlug: 'leilani', body: 'I am in! When works for you?', hoursAfterMatch: 12 },
      { slug: 'leilani-finn-msg-8', senderSlug: 'finn', body: 'Thursday evening? The lap pool at the Y is pretty quiet then.', hoursAfterMatch: 15 },
      { slug: 'leilani-finn-msg-9', senderSlug: 'leilani', body: 'Thursday is perfect. Looking forward to it.', hoursAfterMatch: 17 },
    ],
  },
  {
    slug: 'kai-hana',
    userSlugs: ['kai', 'hana'],
    dayOffset: 13,
    hour: 8,
    isDatingMatch: true,
    messages: [
      { slug: 'kai-hana-msg-1', senderSlug: 'kai', body: 'Your trail photos are incredible. You clearly know the hidden gems.', hoursAfterMatch: 1, isRead: true },
      { slug: 'kai-hana-msg-2', senderSlug: 'hana', body: 'Growing up here helps! I know trails most tourists never find.', hoursAfterMatch: 3, isRead: true },
      { slug: 'kai-hana-msg-3', senderSlug: 'kai', body: 'I have been here two years and still feel like I am discovering new spots.', hoursAfterMatch: 5, isRead: true },
      { slug: 'kai-hana-msg-4', senderSlug: 'hana', body: 'Have you been to Peacock Flats? It is one of my favorites.', hoursAfterMatch: 7, isRead: true },
      { slug: 'kai-hana-msg-5', senderSlug: 'kai', body: 'Never even heard of it. That is exactly what I mean. Can you show me?', hoursAfterMatch: 9, isRead: true },
      { slug: 'kai-hana-msg-6', senderSlug: 'hana', body: 'I would love to. It is an easy hike with an amazing view at the top.', hoursAfterMatch: 11 },
    ],
  },
  {
    slug: 'sora-sakura',
    userSlugs: ['sora', 'sakura'],
    dayOffset: 14,
    hour: 19,
    isDatingMatch: true,
    messages: [
      { slug: 'sora-sakura-msg-1', senderSlug: 'sora', body: 'We both listed swimming and running. Have you thought about doing a triathlon?', hoursAfterMatch: 1, isRead: true },
      { slug: 'sora-sakura-msg-2', senderSlug: 'sakura', body: 'I have been thinking about it! The cycling part scares me though.', hoursAfterMatch: 2, isRead: true },
      { slug: 'sora-sakura-msg-3', senderSlug: 'sora', body: 'Same. Maybe we should train for one together. Accountability helps.', hoursAfterMatch: 4, isRead: true },
      { slug: 'sora-sakura-msg-4', senderSlug: 'sakura', body: 'That is actually a great idea. Sprint distance to start?', hoursAfterMatch: 6, isRead: true },
      { slug: 'sora-sakura-msg-5', senderSlug: 'sora', body: 'Sprint for sure. The Tinman Triathlon is in a few months.', hoursAfterMatch: 8, isRead: true },
      { slug: 'sora-sakura-msg-6', senderSlug: 'sakura', body: 'Let us do it! Training partner and race buddy in one match. Efficient.', hoursAfterMatch: 10, isRead: true },
      { slug: 'sora-sakura-msg-7', senderSlug: 'sora', body: 'Ha, exactly. Want to start with a swim session this week?', hoursAfterMatch: 13 },
      { slug: 'sora-sakura-msg-8', senderSlug: 'sakura', body: 'Wednesday morning? I know a great ocean swim route off Kaimana Beach.', hoursAfterMatch: 16 },
    ],
  },
  {
    slug: 'mae-omar',
    userSlugs: ['mae', 'omar'],
    dayOffset: 16,
    hour: 13,
    isDatingMatch: true,
    messages: [
      { slug: 'mae-omar-msg-1', senderSlug: 'mae', body: 'I love that your bio mentions you play tennis. I have been looking for a hitting partner.', hoursAfterMatch: 1, isRead: true },
      { slug: 'mae-omar-msg-2', senderSlug: 'omar', body: 'Really? That is awesome. What level do you play at?', hoursAfterMatch: 2, isRead: true },
      { slug: 'mae-omar-msg-3', senderSlug: 'mae', body: 'Intermediate. Solid rallies but my serve needs serious help.', hoursAfterMatch: 4, isRead: true },
      { slug: 'mae-omar-msg-4', senderSlug: 'omar', body: 'My serve is my best shot actually. Happy to share tips.', hoursAfterMatch: 6, isRead: true },
      { slug: 'mae-omar-msg-5', senderSlug: 'mae', body: 'Deal! And I can help with your volley game if you need it.', hoursAfterMatch: 8, isRead: true },
      { slug: 'mae-omar-msg-6', senderSlug: 'omar', body: 'Ha, you read my mind. My net game is terrible. When are you free?', hoursAfterMatch: 10 },
      { slug: 'mae-omar-msg-7', senderSlug: 'mae', body: 'Weekday evenings work best. The courts at Ala Moana are lit until 10.', hoursAfterMatch: 13 },
    ],
  },
  {
    slug: 'arden-yara',
    userSlugs: ['arden', 'yara'],
    dayOffset: 17,
    hour: 10,
    isDatingMatch: true,
    messages: [
      { slug: 'arden-yara-msg-1', senderSlug: 'arden', body: 'Your Pilates form is textbook. Do you teach or just really dedicated?', hoursAfterMatch: 1, isRead: true },
      { slug: 'arden-yara-msg-2', senderSlug: 'yara', body: 'Just dedicated! Though people keep telling me I should get certified.', hoursAfterMatch: 2, isRead: true },
      { slug: 'arden-yara-msg-3', senderSlug: 'arden', body: 'You definitely should. What studio do you go to?', hoursAfterMatch: 4, isRead: true },
      { slug: 'arden-yara-msg-4', senderSlug: 'yara', body: 'CorePower in Kailua. The reformer classes there are amazing.', hoursAfterMatch: 6, isRead: true },
      { slug: 'arden-yara-msg-5', senderSlug: 'arden', body: 'I have been meaning to try reformer. Mat Pilates is all I know.', hoursAfterMatch: 8, isRead: true },
      { slug: 'arden-yara-msg-6', senderSlug: 'yara', body: 'Oh you will love it. Game changer for core strength. Want to go together?', hoursAfterMatch: 10, isRead: true },
      { slug: 'arden-yara-msg-7', senderSlug: 'arden', body: 'Would love that. This week sometime?', hoursAfterMatch: 13 },
      { slug: 'arden-yara-msg-8', senderSlug: 'yara', body: 'Friday at 5pm? They have a beginner-friendly reformer class then.', hoursAfterMatch: 16 },
    ],
  },
  {
    slug: 'rowan-mae',
    userSlugs: ['rowan', 'mae'],
    dayOffset: 18,
    hour: 11,
    isDatingMatch: true,
    messages: [
      { slug: 'rowan-mae-msg-1', senderSlug: 'rowan', body: 'Hey Mae, your strength training videos are solid. How long have you been lifting?', hoursAfterMatch: 1, isRead: true },
      { slug: 'rowan-mae-msg-2', senderSlug: 'mae', body: 'About three years. Started during the pandemic and got hooked.', hoursAfterMatch: 3, isRead: true },
      { slug: 'rowan-mae-msg-3', senderSlug: 'rowan', body: 'Classic pandemic gains story. What are your current goals?', hoursAfterMatch: 5, isRead: true },
      { slug: 'rowan-mae-msg-4', senderSlug: 'mae', body: 'Trying to hit a two-plate squat. Currently at 205. So close.', hoursAfterMatch: 7, isRead: true },
      { slug: 'rowan-mae-msg-5', senderSlug: 'rowan', body: 'You are right there! Do you have a spotter? That last bit is mental.', hoursAfterMatch: 9, isRead: true },
      { slug: 'rowan-mae-msg-6', senderSlug: 'mae', body: 'I do not actually. My gym buddy moved to the mainland.', hoursAfterMatch: 11 },
      { slug: 'rowan-mae-msg-7', senderSlug: 'rowan', body: 'I volunteer as tribute. I am at Gold\'s in Honolulu.', hoursAfterMatch: 14 },
    ],
  },

  // ── 10-15 message matches (6) ────────────────────────────────────
  {
    slug: 'kai-nia',
    userSlugs: ['kai', 'nia'],
    dayOffset: 1,
    hour: 10,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      { slug: 'kai-nia-msg-1', senderSlug: 'kai', body: 'Hey Nia! Your bio about combining yoga and weightlifting really resonated with me.', hoursAfterMatch: 1, isRead: true },
      { slug: 'kai-nia-msg-2', senderSlug: 'nia', body: 'Thanks Kai! It is all about balance, right? Hard and soft training.', hoursAfterMatch: 2, isRead: true },
      { slug: 'kai-nia-msg-3', senderSlug: 'kai', body: 'Exactly. I do something similar with running and mobility work. What is your split?', hoursAfterMatch: 4, isRead: true },
      { slug: 'kai-nia-msg-4', senderSlug: 'nia', body: 'Weights four days, yoga three. My body needs the recovery. What about you?', hoursAfterMatch: 6, isRead: true },
      { slug: 'kai-nia-msg-5', senderSlug: 'kai', body: 'Run five days, strength two, rest one. Probably should add more flexibility work.', hoursAfterMatch: 8, isRead: true },
      { slug: 'kai-nia-msg-6', senderSlug: 'nia', body: 'You definitely should! I could show you some yoga flows that complement running.', hoursAfterMatch: 10, isRead: true },
      { slug: 'kai-nia-msg-7', senderSlug: 'kai', body: 'I would honestly love that. Where do you usually practice?', hoursAfterMatch: 12, isRead: true },
      { slug: 'kai-nia-msg-8', senderSlug: 'nia', body: 'At home mostly, but I go to the beach for weekend sessions. There is this perfect spot at Kailua.', hoursAfterMatch: 14, isRead: true },
      { slug: 'kai-nia-msg-9', senderSlug: 'kai', body: 'Kailua is my running route! We have probably passed each other without knowing.', hoursAfterMatch: 16, isRead: true },
      { slug: 'kai-nia-msg-10', senderSlug: 'nia', body: 'Ha, probably! Want to meet there Saturday? I will bring an extra mat.', hoursAfterMatch: 18, isRead: true },
      { slug: 'kai-nia-msg-11', senderSlug: 'kai', body: 'Saturday works perfectly. I will run there and you can fix my downward dog after.', hoursAfterMatch: 20 },
      { slug: 'kai-nia-msg-12', senderSlug: 'nia', body: 'Deal. 8am? We can grab acai bowls at the stand after.', hoursAfterMatch: 22 },
    ],
  },
  {
    slug: 'mason-maren',
    userSlugs: ['mason', 'maren'],
    dayOffset: 5,
    hour: 14,
    isDatingMatch: true,
    messages: [
      { slug: 'mason-maren-msg-1', senderSlug: 'mason', body: 'Maren! Another powerlifter on this app. I was beginning to think I was the only one.', hoursAfterMatch: 1, isRead: true },
      { slug: 'mason-maren-msg-2', senderSlug: 'maren', body: 'Ha, there are dozens of us! What are your current numbers?', hoursAfterMatch: 2, isRead: true },
      { slug: 'mason-maren-msg-3', senderSlug: 'mason', body: 'Squat 405, bench 285, dead 455. Chasing that 1200 total.', hoursAfterMatch: 4, isRead: true },
      { slug: 'mason-maren-msg-4', senderSlug: 'maren', body: 'Impressive! I am at 225, 135, 275 respectively. Different weight class obviously.', hoursAfterMatch: 6, isRead: true },
      { slug: 'mason-maren-msg-5', senderSlug: 'mason', body: 'Those are strong numbers. Do you compete?', hoursAfterMatch: 8, isRead: true },
      { slug: 'mason-maren-msg-6', senderSlug: 'maren', body: 'Did my first meet last year. The platform energy is addictive.', hoursAfterMatch: 10, isRead: true },
      { slug: 'mason-maren-msg-7', senderSlug: 'mason', body: 'I keep saying I will sign up for one. Maybe having someone to prep with would help.', hoursAfterMatch: 12, isRead: true },
      { slug: 'mason-maren-msg-8', senderSlug: 'maren', body: 'Is that a hint? Because I am totally down to be training partners.', hoursAfterMatch: 14, isRead: true },
      { slug: 'mason-maren-msg-9', senderSlug: 'mason', body: 'It was absolutely a hint. Where do you train?', hoursAfterMatch: 16, isRead: true },
      { slug: 'mason-maren-msg-10', senderSlug: 'maren', body: 'Hawaiian Strength and Conditioning. They have comp plates and a deadlift platform.', hoursAfterMatch: 18, isRead: true },
      { slug: 'mason-maren-msg-11', senderSlug: 'mason', body: 'That is only 10 minutes from me. When is your next heavy session?', hoursAfterMatch: 20 },
      { slug: 'mason-maren-msg-12', senderSlug: 'maren', body: 'Tomorrow is squat day. Come at 6pm and I will show you around.', hoursAfterMatch: 22 },
      { slug: 'mason-maren-msg-13', senderSlug: 'mason', body: 'It is a date. Well, a training date. But also maybe a date.', hoursAfterMatch: 24 },
    ],
  },
  {
    slug: 'jordan-alana',
    userSlugs: ['jordan', 'alana'],
    dayOffset: 8,
    hour: 9,
    isDatingMatch: true,
    messages: [
      { slug: 'jordan-alana-msg-1', senderSlug: 'jordan', body: 'Your bio about beach volleyball caught my eye. How competitive do you play?', hoursAfterMatch: 1, isRead: true },
      { slug: 'jordan-alana-msg-2', senderSlug: 'alana', body: 'Competitive enough to hate losing, casual enough to laugh about it. You play?', hoursAfterMatch: 2, isRead: true },
      { slug: 'jordan-alana-msg-3', senderSlug: 'jordan', body: 'Used to play indoor in college. Trying to get back into it with beach.', hoursAfterMatch: 4, isRead: true },
      { slug: 'jordan-alana-msg-4', senderSlug: 'alana', body: 'Indoor players always have such good fundamentals. You will pick up beach fast.', hoursAfterMatch: 6, isRead: true },
      { slug: 'jordan-alana-msg-5', senderSlug: 'jordan', body: 'The sand is a different beast though. My calves were destroyed after my first game.', hoursAfterMatch: 8, isRead: true },
      { slug: 'jordan-alana-msg-6', senderSlug: 'alana', body: 'Ha, sand legs are earned. You will adapt after a few weeks. Worth it for the setting.', hoursAfterMatch: 10, isRead: true },
      { slug: 'jordan-alana-msg-7', senderSlug: 'jordan', body: 'Playing volleyball with an ocean view is hard to beat. Where do you usually play?', hoursAfterMatch: 12, isRead: true },
      { slug: 'jordan-alana-msg-8', senderSlug: 'alana', body: 'Queen\'s Beach courts. We have a regular group on Sunday evenings. Bring sunscreen.', hoursAfterMatch: 14, isRead: true },
      { slug: 'jordan-alana-msg-9', senderSlug: 'jordan', body: 'This Sunday? I am there. Should I bring anything else?', hoursAfterMatch: 16, isRead: true },
      { slug: 'jordan-alana-msg-10', senderSlug: 'alana', body: 'Just a good attitude and maybe a cooler. We usually hang out after and watch the sunset.', hoursAfterMatch: 18 },
      { slug: 'jordan-alana-msg-11', senderSlug: 'jordan', body: 'Volleyball and sunset? You really know how to sell this. See you Sunday.', hoursAfterMatch: 20 },
    ],
  },
  {
    slug: 'leilani-devon',
    userSlugs: ['leilani', 'devon'],
    dayOffset: 10,
    hour: 13,
    isDatingMatch: true,
    messages: [
      { slug: 'leilani-devon-msg-1', senderSlug: 'leilani', body: 'I noticed you do OCR races. I have always been curious about those.', hoursAfterMatch: 1, isRead: true },
      { slug: 'leilani-devon-msg-2', senderSlug: 'devon', body: 'They are so fun! It is like being a kid again but with more mud and walls.', hoursAfterMatch: 3, isRead: true },
      { slug: 'leilani-devon-msg-3', senderSlug: 'leilani', body: 'That actually sounds amazing. What kind of training does it take?', hoursAfterMatch: 5, isRead: true },
      { slug: 'leilani-devon-msg-4', senderSlug: 'devon', body: 'Mix of running and functional strength. Grip training is huge too. Can you do a pull-up?', hoursAfterMatch: 7, isRead: true },
      { slug: 'leilani-devon-msg-5', senderSlug: 'leilani', body: 'Three strict ones! Working toward ten. Grip is definitely my weak spot.', hoursAfterMatch: 9, isRead: true },
      { slug: 'leilani-devon-msg-6', senderSlug: 'devon', body: 'Three is solid. Dead hangs will get your grip up fast. Want me to share my OCR prep program?', hoursAfterMatch: 11, isRead: true },
      { slug: 'leilani-devon-msg-7', senderSlug: 'leilani', body: 'Yes please! Is there an OCR race coming up on the island?', hoursAfterMatch: 13, isRead: true },
      { slug: 'leilani-devon-msg-8', senderSlug: 'devon', body: 'Savage Race in three months. Perfect timeline to train up. We could do it as a team.', hoursAfterMatch: 15, isRead: true },
      { slug: 'leilani-devon-msg-9', senderSlug: 'leilani', body: 'A training partner AND a race goal? You just made my week.', hoursAfterMatch: 17, isRead: true },
      { slug: 'leilani-devon-msg-10', senderSlug: 'devon', body: 'Let me plan out a 12-week program for us. Can we meet this week to talk through it?', hoursAfterMatch: 19 },
      { slug: 'leilani-devon-msg-11', senderSlug: 'leilani', body: 'Thursday evening? There is a great smoothie place near my gym.', hoursAfterMatch: 21 },
      { slug: 'leilani-devon-msg-12', senderSlug: 'devon', body: 'Thursday works. Send me the address and I will be there at 6.', hoursAfterMatch: 23 },
    ],
  },
  {
    slug: 'cole-isla',
    userSlugs: ['cole', 'isla'],
    dayOffset: 15,
    hour: 14,
    isDatingMatch: true,
    isWorkoutMatch: true,
    messages: [
      { slug: 'cole-isla-msg-1', senderSlug: 'cole', body: 'Your adventure racing photos are next level. Where was that river crossing shot?', hoursAfterMatch: 1, isRead: true },
      { slug: 'cole-isla-msg-2', senderSlug: 'isla', body: 'That was the XTERRA Oahu! Best race I have ever done.', hoursAfterMatch: 2, isRead: true },
      { slug: 'cole-isla-msg-3', senderSlug: 'cole', body: 'XTERRA is on my bucket list. How do you even train for something like that?', hoursAfterMatch: 4, isRead: true },
      { slug: 'cole-isla-msg-4', senderSlug: 'isla', body: 'Trail running, mountain biking, and open water swimming. Variety keeps it fun.', hoursAfterMatch: 6, isRead: true },
      { slug: 'cole-isla-msg-5', senderSlug: 'cole', body: 'I do two out of three. Just need to add the mountain biking.', hoursAfterMatch: 8, isRead: true },
      { slug: 'cole-isla-msg-6', senderSlug: 'isla', body: 'The trails at Kaena Point are perfect for MTB. Have you been?', hoursAfterMatch: 10, isRead: true },
      { slug: 'cole-isla-msg-7', senderSlug: 'cole', body: 'Only for hiking. I did not know there were MTB trails there.', hoursAfterMatch: 12, isRead: true },
      { slug: 'cole-isla-msg-8', senderSlug: 'isla', body: 'I will take you! I have a spare bike you can borrow to see if you like it.', hoursAfterMatch: 14, isRead: true },
      { slug: 'cole-isla-msg-9', senderSlug: 'cole', body: 'You have a spare bike? You are officially the coolest person on this app.', hoursAfterMatch: 16, isRead: true },
      { slug: 'cole-isla-msg-10', senderSlug: 'isla', body: 'Ha! I just have too many bikes. Saturday morning work for you?', hoursAfterMatch: 18, isRead: true },
      { slug: 'cole-isla-msg-11', senderSlug: 'cole', body: 'Saturday is perfect. Should I bring anything specific?', hoursAfterMatch: 20, isRead: true },
      { slug: 'cole-isla-msg-12', senderSlug: 'isla', body: 'Helmet if you have one, otherwise I have extras. Water, sunscreen, and a sense of adventure.', hoursAfterMatch: 22 },
      { slug: 'cole-isla-msg-13', senderSlug: 'cole', body: 'Sense of adventure is my middle name. Cannot wait.', hoursAfterMatch: 24 },
    ],
  },
  {
    slug: 'nia-sasha',
    userSlugs: ['nia', 'sasha'],
    dayOffset: 17,
    hour: 15,
    isDatingMatch: true,
    messages: [
      { slug: 'nia-sasha-msg-1', senderSlug: 'nia', body: 'I love your profile. The combo of powerlifting and poetry is unexpected and amazing.', hoursAfterMatch: 1, isRead: true },
      { slug: 'nia-sasha-msg-2', senderSlug: 'sasha', body: 'Thanks! Most people find it contradictory. I think they complement each other.', hoursAfterMatch: 2, isRead: true },
      { slug: 'nia-sasha-msg-3', senderSlug: 'nia', body: 'Totally. Both require discipline, focus, and being comfortable with discomfort.', hoursAfterMatch: 4, isRead: true },
      { slug: 'nia-sasha-msg-4', senderSlug: 'sasha', body: 'Exactly! Nobody has ever put it that way before. What is your creative outlet?', hoursAfterMatch: 6, isRead: true },
      { slug: 'nia-sasha-msg-5', senderSlug: 'nia', body: 'Photography mostly. I love shooting landscapes during morning runs.', hoursAfterMatch: 8, isRead: true },
      { slug: 'nia-sasha-msg-6', senderSlug: 'sasha', body: 'Running photographer? That is a whole vibe. Where do you post your work?', hoursAfterMatch: 10, isRead: true },
      { slug: 'nia-sasha-msg-7', senderSlug: 'nia', body: 'Mostly just my camera roll honestly. I keep meaning to start sharing.', hoursAfterMatch: 12, isRead: true },
      { slug: 'nia-sasha-msg-8', senderSlug: 'sasha', body: 'You should! I would love to see them. Maybe over coffee sometime?', hoursAfterMatch: 14, isRead: true },
      { slug: 'nia-sasha-msg-9', senderSlug: 'nia', body: 'I would like that. Do you know Morning Glass in Manoa?', hoursAfterMatch: 16, isRead: true },
      { slug: 'nia-sasha-msg-10', senderSlug: 'sasha', body: 'Love that place. Their oat milk latte is my weakness.', hoursAfterMatch: 18 },
      { slug: 'nia-sasha-msg-11', senderSlug: 'nia', body: 'Same! Wednesday after my morning run? I will have fresh photos to show you.', hoursAfterMatch: 20 },
    ],
  },

  // ── Archived matches (10 total, mason-rowan-archived above is 1) ──
  // 9 more archived matches needed
  {
    slug: 'noa-beck',
    userSlugs: ['noa', 'beck'],
    dayOffset: 11,
    hour: 17,
    isDatingMatch: true,
    isArchived: true,
    messages: [
      { slug: 'noa-beck-msg-1', senderSlug: 'noa', body: 'Hey! We seem to have a lot in common.', hoursAfterMatch: 1, isRead: true },
    ],
  },
  {
    slug: 'jin-sakura',
    userSlugs: ['jin', 'sakura'],
    dayOffset: 12,
    hour: 8,
    isDatingMatch: true,
    isArchived: true,
    messages: [],
  },
  {
    slug: 'koa-nalani',
    userSlugs: ['koa', 'nalani'],
    dayOffset: 13,
    hour: 11,
    isDatingMatch: true,
    isArchived: true,
    messages: [
      { slug: 'koa-nalani-msg-1', senderSlug: 'koa', body: 'Hey! Want to grab coffee sometime?', hoursAfterMatch: 2, isRead: true },
      { slug: 'koa-nalani-msg-2', senderSlug: 'nalani', body: 'Sure, sounds nice!', hoursAfterMatch: 5, isRead: true },
    ],
  },
  {
    slug: 'hiroshi-mei',
    userSlugs: ['hiroshi', 'mei'],
    dayOffset: 14,
    hour: 9,
    isDatingMatch: true,
    isArchived: true,
    messages: [
      { slug: 'hiroshi-mei-msg-1', senderSlug: 'hiroshi', body: 'Hi Mei, your profile is great. Do you hike often?', hoursAfterMatch: 1, isRead: true },
    ],
  },
  {
    slug: 'makoa-anela',
    userSlugs: ['makoa', 'anela'],
    dayOffset: 15,
    hour: 10,
    isDatingMatch: true,
    isArchived: true,
    messages: [],
  },
  {
    slug: 'keala-hoku',
    userSlugs: ['keala', 'hoku'],
    dayOffset: 16,
    hour: 12,
    isDatingMatch: true,
    isArchived: true,
    messages: [
      { slug: 'keala-hoku-msg-1', senderSlug: 'keala', body: 'Fun matching with you! I saw your climbing photos.', hoursAfterMatch: 1, isRead: true },
      { slug: 'keala-hoku-msg-2', senderSlug: 'hoku', body: 'Thanks! We should climb together sometime.', hoursAfterMatch: 3, isRead: true },
      { slug: 'keala-hoku-msg-3', senderSlug: 'keala', body: 'Definitely. Let me know when you are free.', hoursAfterMatch: 6, isRead: true },
    ],
  },
  {
    slug: 'pua-nalu',
    userSlugs: ['pua', 'nalu'],
    dayOffset: 17,
    hour: 8,
    isDatingMatch: true,
    isArchived: true,
    messages: [
      { slug: 'pua-nalu-msg-1', senderSlug: 'pua', body: 'Nice matching! Your paddleboard photos are awesome.', hoursAfterMatch: 2, isRead: true },
    ],
  },
  {
    slug: 'ikaika-lani',
    userSlugs: ['ikaika', 'lani'],
    dayOffset: 18,
    hour: 15,
    isDatingMatch: true,
    isArchived: true,
    messages: [],
  },
  {
    slug: 'mahina-kalani',
    userSlugs: ['mahina', 'kalani'],
    dayOffset: 19,
    hour: 10,
    isDatingMatch: true,
    isArchived: true,
    messages: [
      { slug: 'mahina-kalani-msg-1', senderSlug: 'mahina', body: 'Hey! Cool that we matched.', hoursAfterMatch: 1, isRead: true },
    ],
  },

  // ── Blocked matches (3) ──────────────────────────────────────────
  {
    slug: 'riko-aiko',
    userSlugs: ['riko', 'aiko'],
    dayOffset: 20,
    hour: 10,
    isDatingMatch: true,
    isBlocked: true,
    messages: [
      { slug: 'riko-aiko-msg-1', senderSlug: 'riko', body: 'Hey there!', hoursAfterMatch: 1, isRead: true },
    ],
  },
  {
    slug: 'yuki-kenji',
    userSlugs: ['yuki', 'kenji'],
    dayOffset: 21,
    hour: 14,
    isDatingMatch: true,
    isBlocked: true,
    messages: [],
  },
  {
    slug: 'hana-sora',
    userSlugs: ['hana', 'sora'],
    dayOffset: 22,
    hour: 11,
    isDatingMatch: true,
    isBlocked: true,
    messages: [
      { slug: 'hana-sora-msg-1', senderSlug: 'hana', body: 'Hi! Nice to match.', hoursAfterMatch: 1, isRead: true },
      { slug: 'hana-sora-msg-2', senderSlug: 'sora', body: 'Hey! Likewise.', hoursAfterMatch: 3, isRead: true },
    ],
  },
];
