import { SeedMatch } from './config';

/**
 * 50 workout-focused matches for the BRDG fitness dating app.
 *
 * Distribution:
 *   10 matches  -  0 messages
 *   15 matches  -  1-2 messages
 *   15 matches  -  3-5 messages
 *    7 matches  -  6-8 messages
 *    3 matches  -  9-12 messages
 *
 * Special states: 5 archived, 2 blocked.
 * All matches: isWorkoutMatch = true, isDatingMatch = false.
 */
export const workoutMatches: SeedMatch[] = [
  // ─── 0 messages (10 matches) ────────────────────────────────────
  {
    slug: 'wo-kai-akira',
    userSlugs: ['kai', 'akira'],
    dayOffset: 0,
    hour: 7,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [],
  },
  {
    slug: 'wo-leilani-hana',
    userSlugs: ['leilani', 'hana'],
    dayOffset: 1,
    hour: 9,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [],
  },
  {
    slug: 'wo-mason-kenji',
    userSlugs: ['mason', 'kenji'],
    dayOffset: 2,
    hour: 11,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [],
  },
  {
    slug: 'wo-nia-mika',
    userSlugs: ['nia', 'mika'],
    dayOffset: 3,
    hour: 6,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [],
  },
  {
    slug: 'wo-jordan-sora',
    userSlugs: ['jordan', 'sora'],
    dayOffset: 4,
    hour: 14,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [],
  },
  {
    slug: 'wo-malia-yuki',
    userSlugs: ['malia', 'yuki'],
    dayOffset: 5,
    hour: 17,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [],
  },
  {
    slug: 'wo-rowan-taro',
    userSlugs: ['rowan', 'taro'],
    dayOffset: 6,
    hour: 8,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [],
  },
  {
    slug: 'wo-tessa-riko',
    userSlugs: ['tessa', 'riko'],
    dayOffset: 7,
    hour: 19,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [],
  },
  {
    slug: 'wo-keoni-aiko',
    userSlugs: ['keoni', 'aiko'],
    dayOffset: 8,
    hour: 10,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [],
  },
  {
    slug: 'wo-sasha-hiroshi',
    userSlugs: ['sasha', 'hiroshi'],
    dayOffset: 9,
    hour: 15,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [],
  },

  // ─── 1-2 messages (15 matches) ──────────────────────────────────
  {
    slug: 'wo-eli-mei',
    userSlugs: ['eli', 'mei'],
    dayOffset: 0,
    hour: 12,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'wo-eli-mei-msg-1',
        senderSlug: 'eli',
        body: 'Hey! I saw you do a lot of strength training. What gym do you usually go to?',
        hoursAfterMatch: 1,
        isRead: true,
      },
    ],
  },
  {
    slug: 'wo-alana-jin',
    userSlugs: ['alana', 'jin'],
    dayOffset: 1,
    hour: 16,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'wo-alana-jin-msg-1',
        senderSlug: 'jin',
        body: 'Your trail running photos are awesome. Do you usually run Diamond Head?',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'wo-alana-jin-msg-2',
        senderSlug: 'alana',
        body: 'Yes! Usually Saturday mornings around 6. You should join sometime.',
        hoursAfterMatch: 3,
        isRead: false,
      },
    ],
  },
  {
    slug: 'wo-devon-sakura',
    userSlugs: ['devon', 'sakura'],
    dayOffset: 2,
    hour: 7,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'wo-devon-sakura-msg-1',
        senderSlug: 'devon',
        body: 'I noticed we both do boxing. Do you train at the same place on King St?',
        hoursAfterMatch: 1,
        isRead: true,
      },
    ],
  },
  {
    slug: 'wo-priya-koa',
    userSlugs: ['priya', 'koa'],
    dayOffset: 3,
    hour: 18,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'wo-priya-koa-msg-1',
        senderSlug: 'koa',
        body: 'Aloha! Looking for a swim buddy for open water. Interested?',
        hoursAfterMatch: 4,
        isRead: true,
      },
      {
        slug: 'wo-priya-koa-msg-2',
        senderSlug: 'priya',
        body: 'Absolutely! I usually swim at Ala Moana on weekday mornings.',
        hoursAfterMatch: 6,
        isRead: true,
      },
    ],
  },
  {
    slug: 'wo-cole-lani',
    userSlugs: ['cole', 'lani'],
    dayOffset: 4,
    hour: 8,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'wo-cole-lani-msg-1',
        senderSlug: 'cole',
        body: 'What days do you usually hit the climbing gym?',
        hoursAfterMatch: 2,
        isRead: false,
      },
    ],
  },
  {
    slug: 'wo-maren-makoa',
    userSlugs: ['maren', 'makoa'],
    dayOffset: 5,
    hour: 20,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'wo-maren-makoa-msg-1',
        senderSlug: 'makoa',
        body: 'Saw you paddle outrigger! I crew on a six-man and we need subs.',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'wo-maren-makoa-msg-2',
        senderSlug: 'maren',
        body: 'That sounds amazing. What time do you practice?',
        hoursAfterMatch: 3,
        isRead: false,
      },
    ],
  },
  {
    slug: 'wo-noa-nalani',
    userSlugs: ['noa', 'nalani'],
    dayOffset: 6,
    hour: 13,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'wo-noa-nalani-msg-1',
        senderSlug: 'noa',
        body: 'I am training for a half marathon. Want to do long runs together on Sundays?',
        hoursAfterMatch: 5,
        isRead: true,
      },
    ],
  },
  {
    slug: 'wo-cameron-kekoa',
    userSlugs: ['cameron', 'kekoa'],
    dayOffset: 7,
    hour: 6,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'wo-cameron-kekoa-msg-1',
        senderSlug: 'kekoa',
        body: 'Brah, your surf game is solid. Wanna paddle out at Walls this weekend?',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'wo-cameron-kekoa-msg-2',
        senderSlug: 'cameron',
        body: 'Down! Saturday sunrise works for me.',
        hoursAfterMatch: 4,
        isRead: true,
      },
    ],
  },
  {
    slug: 'wo-isla-hoku',
    userSlugs: ['isla', 'hoku'],
    dayOffset: 8,
    hour: 9,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'wo-isla-hoku-msg-1',
        senderSlug: 'isla',
        body: 'Do you have a favorite yoga studio? I just moved here and am looking for recommendations.',
        hoursAfterMatch: 1,
        isRead: true,
      },
    ],
  },
  {
    slug: 'wo-rafael-mahina',
    userSlugs: ['rafael', 'mahina'],
    dayOffset: 10,
    hour: 11,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'wo-rafael-mahina-msg-1',
        senderSlug: 'rafael',
        body: 'I see you do HIIT. I lead a bootcamp in Kapiolani Park on Tuesdays. Come through!',
        hoursAfterMatch: 3,
        isRead: false,
      },
    ],
  },
  {
    slug: 'wo-ivy-anela',
    userSlugs: ['ivy', 'anela'],
    dayOffset: 11,
    hour: 14,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'wo-ivy-anela-msg-1',
        senderSlug: 'anela',
        body: 'Your pilates form looks great! Want to try the reformer class at Core Power?',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'wo-ivy-anela-msg-2',
        senderSlug: 'ivy',
        body: 'Yes please! I have been wanting to try reformer. When are you free?',
        hoursAfterMatch: 5,
        isRead: true,
      },
    ],
  },
  {
    slug: 'wo-beck-ikaika',
    userSlugs: ['beck', 'ikaika'],
    dayOffset: 12,
    hour: 7,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'wo-beck-ikaika-msg-1',
        senderSlug: 'beck',
        body: 'Thinking about signing up for the Spartan race next month. You in?',
        hoursAfterMatch: 1,
        isRead: true,
      },
    ],
  },
  {
    slug: 'wo-june-kalani',
    userSlugs: ['june', 'kalani'],
    dayOffset: 13,
    hour: 16,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'wo-june-kalani-msg-1',
        senderSlug: 'kalani',
        body: 'Your volleyball skills look solid! We play pickup at Queens Beach on Saturdays.',
        hoursAfterMatch: 3,
        isRead: true,
      },
      {
        slug: 'wo-june-kalani-msg-2',
        senderSlug: 'june',
        body: 'I will be there this Saturday! What time does it usually start?',
        hoursAfterMatch: 5,
        isRead: false,
      },
    ],
  },
  {
    slug: 'wo-luca-keala',
    userSlugs: ['luca', 'keala'],
    dayOffset: 14,
    hour: 10,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'wo-luca-keala-msg-1',
        senderSlug: 'luca',
        body: 'What is your current bench PR? I am trying to hit 225 by summer.',
        hoursAfterMatch: 2,
        isRead: true,
      },
    ],
  },
  {
    slug: 'wo-arden-nalu',
    userSlugs: ['arden', 'nalu'],
    dayOffset: 15,
    hour: 19,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'wo-arden-nalu-msg-1',
        senderSlug: 'nalu',
        body: 'Morning paddler here. Wanna try a dawn session at Kailua?',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'wo-arden-nalu-msg-2',
        senderSlug: 'arden',
        body: 'That is my favorite spot! I am usually there by 5:30.',
        hoursAfterMatch: 4,
        isRead: true,
      },
    ],
  },

  // ─── 3-5 messages (15 matches) ──────────────────────────────────
  {
    slug: 'wo-hazel-pua',
    userSlugs: ['hazel', 'pua'],
    dayOffset: 0,
    hour: 15,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'wo-hazel-pua-msg-1',
        senderSlug: 'hazel',
        body: 'I love that you are into hiking! What is the best trail you have done recently?',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'wo-hazel-pua-msg-2',
        senderSlug: 'pua',
        body: 'Koko Head at sunrise is unbeatable. Have you done it?',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'wo-hazel-pua-msg-3',
        senderSlug: 'hazel',
        body: 'Not yet! I have been meaning to. Want to do it this weekend?',
        hoursAfterMatch: 4,
        isRead: true,
      },
    ],
  },
  {
    slug: 'wo-omar-tia',
    userSlugs: ['omar', 'tia'],
    dayOffset: 1,
    hour: 8,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'wo-omar-tia-msg-1',
        senderSlug: 'omar',
        body: 'Do you follow any particular lifting program? I am running 5/3/1 right now.',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'wo-omar-tia-msg-2',
        senderSlug: 'tia',
        body: 'Nice! I am on a PPL split. How are you liking the progression?',
        hoursAfterMatch: 3,
        isRead: true,
      },
      {
        slug: 'wo-omar-tia-msg-3',
        senderSlug: 'omar',
        body: 'Loving it. My squat has gone up 20 lbs in two months.',
        hoursAfterMatch: 5,
        isRead: true,
      },
      {
        slug: 'wo-omar-tia-msg-4',
        senderSlug: 'tia',
        body: 'That is solid progress! Maybe we can spot each other sometime.',
        hoursAfterMatch: 7,
        isRead: false,
      },
    ],
  },
  {
    slug: 'wo-celine-rafa',
    userSlugs: ['celine', 'rafa'],
    dayOffset: 2,
    hour: 18,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'wo-celine-rafa-msg-1',
        senderSlug: 'celine',
        body: 'Hey! I am looking for a cycling partner for weekend rides. Are you into road or gravel?',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'wo-celine-rafa-msg-2',
        senderSlug: 'rafa',
        body: 'Road mostly! I usually do the Tantalus loop. About 25 miles round trip.',
        hoursAfterMatch: 4,
        isRead: true,
      },
      {
        slug: 'wo-celine-rafa-msg-3',
        senderSlug: 'celine',
        body: 'Perfect pace for me. Sunday morning work?',
        hoursAfterMatch: 6,
        isRead: true,
      },
    ],
  },
  {
    slug: 'wo-leo-nina',
    userSlugs: ['leo', 'nina'],
    dayOffset: 3,
    hour: 10,
    isDatingMatch: false,
    isWorkoutMatch: true,
    isArchived: true,
    messages: [
      {
        slug: 'wo-leo-nina-msg-1',
        senderSlug: 'leo',
        body: 'Just finished a killer leg day. What is your go-to leg workout?',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'wo-leo-nina-msg-2',
        senderSlug: 'nina',
        body: 'Bulgarian split squats are my nemesis but they work. Plus hip thrusts.',
        hoursAfterMatch: 3,
        isRead: true,
      },
      {
        slug: 'wo-leo-nina-msg-3',
        senderSlug: 'leo',
        body: 'Same! I also throw in some Nordic hamstring curls.',
        hoursAfterMatch: 5,
        isRead: true,
      },
      {
        slug: 'wo-leo-nina-msg-4',
        senderSlug: 'nina',
        body: 'Those are brutal. Respect.',
        hoursAfterMatch: 7,
        isRead: true,
      },
      {
        slug: 'wo-leo-nina-msg-5',
        senderSlug: 'leo',
        body: 'We should do a leg day together sometime and push each other.',
        hoursAfterMatch: 9,
        isRead: true,
      },
    ],
  },
  {
    slug: 'wo-nora-marco',
    userSlugs: ['nora', 'marco'],
    dayOffset: 4,
    hour: 22,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'wo-nora-marco-msg-1',
        senderSlug: 'nora',
        body: 'I see you are into mobility work. I have been trying to improve my squat depth.',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'wo-nora-marco-msg-2',
        senderSlug: 'marco',
        body: 'Hip flexor and ankle mobility drills are game changers. Want me to share my routine?',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'wo-nora-marco-msg-3',
        senderSlug: 'nora',
        body: 'Yes please! I have been foam rolling but it is not enough.',
        hoursAfterMatch: 4,
        isRead: true,
      },
    ],
  },
  {
    slug: 'wo-finn-dani',
    userSlugs: ['finn', 'dani'],
    dayOffset: 5,
    hour: 13,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'wo-finn-dani-msg-1',
        senderSlug: 'finn',
        body: 'How often do you swim per week? I am trying to build up to 5 days.',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'wo-finn-dani-msg-2',
        senderSlug: 'dani',
        body: 'I do 4 mornings before work. Consistency is key. Start with 3 and build up.',
        hoursAfterMatch: 3,
        isRead: true,
      },
      {
        slug: 'wo-finn-dani-msg-3',
        senderSlug: 'finn',
        body: 'Good advice. What pool do you go to?',
        hoursAfterMatch: 5,
        isRead: true,
      },
      {
        slug: 'wo-finn-dani-msg-4',
        senderSlug: 'dani',
        body: 'Palolo Valley pool. Lanes are usually open at 5:30 AM.',
        hoursAfterMatch: 6,
        isRead: false,
      },
    ],
  },
  {
    slug: 'wo-mae-sol',
    userSlugs: ['mae', 'sol'],
    dayOffset: 7,
    hour: 11,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'wo-mae-sol-msg-1',
        senderSlug: 'mae',
        body: 'Your dance fitness videos look so fun. What style is it?',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'wo-mae-sol-msg-2',
        senderSlug: 'sol',
        body: 'Mix of dancehall and Afrobeats cardio! Burns way more calories than the treadmill.',
        hoursAfterMatch: 3,
        isRead: true,
      },
      {
        slug: 'wo-mae-sol-msg-3',
        senderSlug: 'mae',
        body: 'I need that in my life. Any classes near Kailua?',
        hoursAfterMatch: 5,
        isRead: true,
      },
    ],
  },
  {
    slug: 'wo-remy-zara',
    userSlugs: ['remy', 'zara'],
    dayOffset: 9,
    hour: 6,
    isDatingMatch: false,
    isWorkoutMatch: true,
    isArchived: true,
    messages: [
      {
        slug: 'wo-remy-zara-msg-1',
        senderSlug: 'remy',
        body: 'Are you training for any races coming up?',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'wo-remy-zara-msg-2',
        senderSlug: 'zara',
        body: 'The Honolulu Triathlon in June! Just started my brick workouts.',
        hoursAfterMatch: 3,
        isRead: true,
      },
      {
        slug: 'wo-remy-zara-msg-3',
        senderSlug: 'remy',
        body: 'No way, me too! Sprint or Olympic distance?',
        hoursAfterMatch: 4,
        isRead: true,
      },
      {
        slug: 'wo-remy-zara-msg-4',
        senderSlug: 'zara',
        body: 'Olympic. Swim is my weakest leg though.',
        hoursAfterMatch: 6,
        isRead: true,
      },
      {
        slug: 'wo-remy-zara-msg-5',
        senderSlug: 'remy',
        body: 'We should train together. I can help with swim drills.',
        hoursAfterMatch: 8,
        isRead: true,
      },
    ],
  },
  {
    slug: 'wo-yara-jax',
    userSlugs: ['yara', 'jax'],
    dayOffset: 10,
    hour: 17,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'wo-yara-jax-msg-1',
        senderSlug: 'yara',
        body: 'What is your favorite post-workout meal? I need new ideas.',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'wo-yara-jax-msg-2',
        senderSlug: 'jax',
        body: 'Acai bowl from the spot on Monsarrat. Tons of protein if you add peanut butter.',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'wo-yara-jax-msg-3',
        senderSlug: 'yara',
        body: 'Sold. Want to grab one after a morning run this week?',
        hoursAfterMatch: 4,
        isRead: false,
      },
    ],
  },
  {
    slug: 'wo-luna-ash',
    userSlugs: ['luna', 'ash'],
    dayOffset: 14,
    hour: 20,
    isDatingMatch: false,
    isWorkoutMatch: true,
    isArchived: true,
    messages: [
      {
        slug: 'wo-luna-ash-msg-1',
        senderSlug: 'luna',
        body: 'Are you into bouldering or top rope?',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'wo-luna-ash-msg-2',
        senderSlug: 'ash',
        body: 'Both! Bouldering for power, top rope for endurance. You?',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'wo-luna-ash-msg-3',
        senderSlug: 'luna',
        body: 'Mostly bouldering. I project V5s right now.',
        hoursAfterMatch: 4,
        isRead: true,
      },
    ],
  },
  {
    slug: 'wo-zeke-tate',
    userSlugs: ['zeke', 'tate'],
    dayOffset: 2,
    hour: 13,
    isDatingMatch: false,
    isWorkoutMatch: true,
    messages: [
      {
        slug: 'wo-zeke-tate-msg-1',
        senderSlug: 'zeke',
        body: 'Your deadlift form in that video was clean. What program are you running?',
        hoursAfterMatch: 1,
        isRead: true,
      },
      {
        slug: 'wo-zeke-tate-msg-2',
        senderSlug: 'tate',
        body: 'Thanks! Running a modified Texas Method. Great for intermediate lifters.',
        hoursAfterMatch: 2,
        isRead: true,
      },
      {
        slug: 'wo-zeke-tate-msg-3',
        senderSlug: 'zeke',
        body: 'I have been stuck on a plateau. Maybe I should switch from linear progression.',
        hoursAfterMatch: 4,
        isRead: true,
      },
      {
        slug: 'wo-zeke-tate-msg-4',
        senderSlug: 'tate',
        body: 'Definitely. Periodization is key once you stall on LP. What are your current numbers?',
        hoursAfterMatch: 5,
        isRead: true,
      },
      {
        slug: 'wo-zeke-tate-msg-5',
        senderSlug: 'zeke',
        body: 'Squat 315, bench 225, deadlift 365. Want to hit 4 plates on DL.',
        hoursAfterMatch: 7,
        isRead: true,
      },
      {
        slug: 'wo-zeke-tate-msg-6',
        senderSlug: 'tate',
        body: 'Those are solid. You could hit 405 in a few months with the right programming.',
        hoursAfterMatch: 8,
        isRead: true,
      },
      {
        slug: 'wo-zeke-tate-msg-7',
        senderSlug: 'zeke',
        body: 'Want to train together this Saturday? I go to Iron Works on Kapahulu.',
        hoursAfterMatch: 10,
        isRead: false,
      },
    ],
  },];
