import type { Meta, StoryObj } from '@storybook/react-native';
import { ProfileScreenContent } from '../features/profile/components/ProfileScreenContent';

const meta = {
  title: 'Profile/BuildInfo',
  component: ProfileScreenContent,
  parameters: {
    backgrounds: { default: 'light', values: [{ name: 'light', value: '#FDFBF8' }] },
  },
} satisfies Meta<typeof ProfileScreenContent>;

export default meta;
type Story = StoryObj<typeof meta>;

export const Expanded: Story = {
  args: {
    completenessScore: 75,
    completenessMissing: [],
    deletingAccount: false,
    editingPhotos: false,
    bio: 'Early starts, surf checks, and low-pressure plans.',
    city: 'Honolulu',
    editMode: false,
    errorMessage: null,
    discoveryPreference: 'both',
    intensityLevel: 'moderate',
    intentDating: true,
    intentFriends: false,
    intentWorkout: true,
    isRefetching: false,
    isSavingProfile: false,
    isSavingFitness: false,
    knownLocationSuggestions: [],
    navigation: { navigate: () => undefined },
    onCancelEdit: () => undefined,
    onConfirmDeleteAccount: () => undefined,
    onDeletePhoto: () => undefined,
    onMakePrimaryPhoto: () => undefined,
    onMovePhotoLeft: () => undefined,
    onMovePhotoRight: () => undefined,
    onLogout: () => undefined,
    onRefresh: () => undefined,
    onSave: () => undefined,
    onSetBio: () => undefined,
    onSetCity: () => undefined,
    onSelectCitySuggestion: () => undefined,
    onSetDiscoveryPreference: () => undefined,
    onSetIntensityLevel: () => undefined,
    onSetIntentDating: () => undefined,
    onSetIntentFriends: () => undefined,
    onSetIntentWorkout: () => undefined,
    onSetPrimaryGoal: () => undefined,
    onSetSelectedActivities: () => undefined,
    onSetSelectedSchedule: () => undefined,
    onSetWeeklyFrequencyBand: () => undefined,
    onToggleBuildInfo: () => undefined,
    onUploadPhoto: () => undefined,
    photoOperation: null,
    primaryGoal: 'connection',
    profile: {
      id: 'user-1',
      firstName: 'Jordan',
      age: 29,
      profile: { city: 'Honolulu' },
      fitnessProfile: {
        intensityLevel: 'moderate',
        weeklyFrequencyBand: '3-4',
        primaryGoal: 'connection',
        favoriteActivities: 'Running, Surfing',
        prefersMorning: true,
        prefersEvening: false,
      },
      photos: [],
    } as any,
    selectedActivities: ['Running', 'Surfing'],
    selectedSchedule: ['Morning'],
    showBuildInfo: true,
    weeklyFrequencyBand: '3-4',
  },
};
