import { Dimensions, StyleSheet } from 'react-native';
import { lightTheme, radii, spacing, typography } from '../../../theme/tokens';

const SCREEN_WIDTH = Dimensions.get('window').width;
const PHOTO_GALLERY_WIDTH = SCREEN_WIDTH - spacing.xxl * 2;
const PHOTO_SECONDARY_CARD_WIDTH = (PHOTO_GALLERY_WIDTH - spacing.sm) / 2;

// Static references for StyleSheet (module-level); components use useTheme() for reactivity
const BASE = lightTheme.background;
const SURFACE = lightTheme.surface;
const SURFACE_ELEVATED = lightTheme.surfaceElevated;
const BORDER = lightTheme.border;
const PRIMARY = lightTheme.primary;
const ACCENT_TEXT = '#8B6A42';
const TEXT_PRIMARY = lightTheme.textPrimary;
const TEXT_SECONDARY = lightTheme.textSecondary;
const TEXT_MUTED = lightTheme.textMuted;
const DANGER = lightTheme.danger;

const SOFT_SHADOW = {
  shadowColor: '#B0A89E',
  shadowOpacity: 0.16,
  shadowRadius: 12,
  shadowOffset: { width: 0, height: 2 },
  elevation: 3,
} as const;

export const profileStyles = StyleSheet.create({
  container: { flex: 1, backgroundColor: BASE },
  heroBg: {
    position: 'absolute',
    top: -80,
    left: SCREEN_WIDTH / 2 - 150,
    width: 300,
    height: 300,
    borderRadius: 150,
    backgroundColor: '#E8DFD0',
    opacity: 0.04,
  },
  scrollContent: { paddingBottom: 100 },
  hero: { marginBottom: spacing.lg },
  heroPhotoWrap: {
    width: SCREEN_WIDTH,
    height: 260,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    overflow: 'hidden',
    backgroundColor: SURFACE_ELEVATED,
  },
  heroPhoto: { width: '100%', height: '100%' },
  heroFallback: {
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  heroFallbackText: { fontSize: 64, fontWeight: '900', color: '#FFFFFF' },
  heroOverlay: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    paddingHorizontal: spacing.xxl,
    paddingBottom: spacing.lg,
    paddingTop: 60,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    overflow: 'hidden',
  },
  heroCopyCard: {
    alignSelf: 'flex-start',
    maxWidth: '82%',
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderRadius: 24,
    backgroundColor: 'rgba(253,251,248,0.74)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.5)',
  },
  heroName: { fontSize: 28, fontWeight: '900', letterSpacing: -0.8, color: TEXT_PRIMARY, marginBottom: spacing.xs },
  intentBadge: {
    alignSelf: 'flex-start',
    backgroundColor: 'rgba(196,168,130,0.2)',
    borderRadius: radii.pill,
    paddingHorizontal: spacing.md,
    paddingVertical: 5,
    marginBottom: spacing.xs,
  },
  intentBadgeText: { fontSize: typography.bodySmall, fontWeight: '800', color: ACCENT_TEXT },
  heroLocation: { fontSize: typography.bodySmall, color: TEXT_SECONDARY, fontWeight: '600' },
  ambientStats: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: spacing.lg, paddingTop: spacing.lg },
  ambientStat: { alignItems: 'center' },
  ambientStatNum: { fontSize: 32, fontWeight: '900', letterSpacing: -1, lineHeight: 36, color: TEXT_PRIMARY },
  ambientStatLabel: { fontSize: 10, fontWeight: '700', color: TEXT_MUTED, textTransform: 'uppercase', letterSpacing: 0.8, marginTop: 2 },
  ambientStatDot: { width: 4, height: 4, borderRadius: 2, backgroundColor: BORDER },
  editBar: { flexDirection: 'row', paddingHorizontal: spacing.xxl, marginBottom: spacing.xxl, gap: spacing.sm, alignItems: 'center' },
  editBtnWrap: { flex: 1, borderRadius: 999, overflow: 'hidden', paddingVertical: 11, alignItems: 'center', backgroundColor: 'rgba(0,0,0,0.04)' },
  editBtnActive: { backgroundColor: '#C4A882' },
  editBtnText: { fontSize: typography.bodySmall, fontWeight: '900', letterSpacing: 0.2, color: TEXT_PRIMARY },
  editBtnTextActive: { color: '#FFFFFF' },
  cancelBtn: { paddingHorizontal: spacing.md, paddingVertical: 11, borderRadius: radii.pill, backgroundColor: 'rgba(0,0,0,0.05)' },
  cancelBtnText: { fontSize: typography.bodySmall, fontWeight: '700', color: TEXT_MUTED },
  section: { paddingHorizontal: spacing.xxl, marginBottom: spacing.xxl },
  sectionEyebrow: { fontSize: 10, fontWeight: '900', textTransform: 'uppercase', letterSpacing: 1.5, color: TEXT_MUTED, marginBottom: spacing.md },
  tagCloud: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  tagPill: { paddingHorizontal: 14, paddingVertical: 7, borderRadius: radii.pill },
  tagPillText: { fontSize: 13, fontWeight: '700', color: TEXT_PRIMARY },
  fieldsCard: { backgroundColor: SURFACE, borderRadius: 16, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, ...SOFT_SHADOW },
  fieldRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: spacing.sm, gap: spacing.md },
  fieldLabel: { fontSize: typography.bodySmall, fontWeight: '700', width: 100, color: TEXT_MUTED, textTransform: 'capitalize' },
  fieldValue: { flex: 1, fontSize: typography.bodySmall, fontWeight: '600', textTransform: 'capitalize', color: TEXT_PRIMARY },
  fieldInput: { flex: 1, fontSize: typography.bodySmall, borderWidth: 1, borderRadius: radii.sm, paddingHorizontal: spacing.sm, paddingVertical: 5, borderColor: 'rgba(196,168,130,0.2)', backgroundColor: 'rgba(196,168,130,0.04)', color: TEXT_PRIMARY },
  fieldInputMultiline: { minHeight: 86, paddingTop: spacing.sm },
  fieldDivider: { height: 1, backgroundColor: 'rgba(0,0,0,0.06)' },
  photoManager: { gap: spacing.md },
  photoIntro: { gap: spacing.xs, padding: spacing.md, borderRadius: 18, backgroundColor: 'rgba(0,0,0,0.02)', ...SOFT_SHADOW },
  photoIntroTitle: { fontSize: typography.bodySmall, fontWeight: '800', color: TEXT_PRIMARY },
  photoIntroBody: { fontSize: typography.caption, lineHeight: 18, color: TEXT_SECONDARY },
  photoProgressTrack: { height: 6, borderRadius: radii.pill, backgroundColor: 'rgba(0,0,0,0.06)', overflow: 'hidden', marginTop: 2 },
  photoProgressFill: { height: '100%', borderRadius: radii.pill, backgroundColor: PRIMARY },
  photoGrid: { gap: spacing.md },
  photoSecondaryGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  photoEmptyCard: { borderRadius: 18, backgroundColor: SURFACE, padding: spacing.lg, gap: spacing.xs, ...SOFT_SHADOW },
  photoEmptyTitle: { fontSize: typography.bodySmall, fontWeight: '800', color: TEXT_PRIMARY },
  photoEmptyBody: { fontSize: typography.caption, lineHeight: 18, color: TEXT_SECONDARY },
  photoGalleryCardShell: {
    borderRadius: 24,
    backgroundColor: SURFACE,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.04)',
    ...SOFT_SHADOW,
  },
  photoGalleryCardShellPrimary: { width: '100%' },
  photoGalleryCardShellSecondary: { width: PHOTO_SECONDARY_CARD_WIDTH },
  photoGalleryCard: {
    borderRadius: 24,
    overflow: 'hidden',
    backgroundColor: SURFACE,
  },
  photoCardActive: {
    borderWidth: 1,
    borderColor: 'rgba(196,168,130,0.4)',
    backgroundColor: 'rgba(196,168,130,0.05)',
  },
  photoMedia: { position: 'relative' },
  photoGalleryImage: { width: '100%', backgroundColor: BASE },
  photoGalleryImagePrimary: { height: 252 },
  photoGalleryImageSecondary: { aspectRatio: 1 },
  photoBadgeRow: { position: 'absolute', top: spacing.sm, left: spacing.sm },
  photoMeta: { gap: spacing.sm, padding: spacing.md },
  photoHeaderMeta: { flex: 1, gap: 2 },
  photoLabel: { fontSize: typography.bodySmall, fontWeight: '800', color: TEXT_PRIMARY },
  photoSlotText: { fontSize: typography.caption, color: TEXT_MUTED, fontWeight: '600' },
  photoSlotPill: {
    paddingHorizontal: spacing.sm,
    paddingVertical: 5,
    borderRadius: radii.pill,
    backgroundColor: 'rgba(253,251,248,0.88)',
    borderWidth: 1,
    borderColor: 'rgba(92,84,76,0.08)',
  },
  photoSlotPillText: { fontSize: 11, fontWeight: '800', color: TEXT_SECONDARY, letterSpacing: 0.3 },
  photoPrimaryPill: { backgroundColor: 'rgba(253,251,248,0.94)', borderColor: 'rgba(196,168,130,0.35)' },
  photoPrimaryPillText: { color: PRIMARY },
  photoInlineStatus: { flexDirection: 'row', alignItems: 'center', gap: 6, paddingHorizontal: spacing.sm, paddingVertical: 8, borderRadius: 12, backgroundColor: 'rgba(196,168,130,0.08)', borderWidth: 1, borderColor: 'rgba(196,168,130,0.24)' },
  photoInlineStatusText: { fontSize: typography.caption, fontWeight: '700', color: TEXT_PRIMARY },
  photoActionsCompact: { flexDirection: 'row', flexWrap: 'wrap', gap: 4 },
  photoActionButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.05)',
  },
  photoActionButtonDanger: {
    backgroundColor: 'rgba(201,112,112,0.06)',
    borderWidth: 1,
    borderColor: 'rgba(201,112,112,0.2)',
  },
  photoActionButtonDisabled: { opacity: 0.7 },
  settingsCard: { backgroundColor: SURFACE, borderRadius: 16, paddingHorizontal: spacing.md, paddingVertical: spacing.sm, ...SOFT_SHADOW },
  settingsRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 13, gap: spacing.md },
  settingsIcon: { fontSize: 18, width: 24, textAlign: 'center' },
  settingsLabel: { flex: 1, fontSize: typography.body, fontWeight: '700', color: TEXT_PRIMARY },
  settingsArrow: { fontSize: 22, fontWeight: '300', color: TEXT_MUTED },
  buildInfoCard: { paddingTop: spacing.sm, gap: spacing.xs },
  buildInfoRow: { gap: 4, paddingVertical: spacing.sm },
  buildInfoLabel: { fontSize: typography.bodySmall, fontWeight: '700', color: TEXT_MUTED, textTransform: 'uppercase', letterSpacing: 0.6 },
  buildInfoValue: { fontSize: typography.bodySmall, lineHeight: 20, color: TEXT_PRIMARY, fontWeight: '600' },
  buildInfoDivider: { height: 1, backgroundColor: BORDER },
  dangerCard: { backgroundColor: 'rgba(201,112,112,0.04)', borderWidth: 1, borderColor: 'rgba(201,112,112,0.16)', borderRadius: 24, padding: spacing.xl, gap: spacing.md },
  dangerTitle: { fontSize: typography.body, fontWeight: '800', color: TEXT_PRIMARY },
  dangerBody: { fontSize: typography.bodySmall, lineHeight: 20, color: TEXT_SECONDARY },
  deleteAccountBtn: { minHeight: 46, borderRadius: radii.pill, alignItems: 'center', justifyContent: 'center', backgroundColor: DANGER },
  deleteAccountBtnPressed: { opacity: 0.88 },
  deleteAccountBtnDisabled: { opacity: 0.6 },
  deleteAccountText: { fontSize: typography.bodySmall, fontWeight: '800', color: '#FFFFFF' },
  errorBanner: { marginHorizontal: spacing.xxl, borderWidth: 1, borderRadius: 12, padding: spacing.md, marginBottom: spacing.sm, backgroundColor: 'rgba(201,112,112,0.06)', borderColor: 'rgba(201,112,112,0.16)' },
  errorText: { fontSize: typography.bodySmall, fontWeight: '600', color: DANGER },
  logoutBtn: { alignItems: 'center', paddingVertical: spacing.xl, marginTop: spacing.sm },
  logoutText: { fontSize: typography.body, fontWeight: '800', color: DANGER, letterSpacing: 0.2 },
});
